import { describe, expect, it } from "vitest";
import { buildOneDayMenuPdfDocument } from "../src/main/one-day-menu-pdf";
import type { CatalogCategory, CatalogItem, Publication, RuntimeConfig } from "../src/shared/contracts";

const categories: CatalogCategory[] = [{ id: "chaat", name: "Chaat & Street Food", order: 1, active: true }, { id: "hidden", name: "Hidden", order: 2, active: false }];
const item = (id: string, overrides: Partial<CatalogItem> = {}): CatalogItem => ({ id, categoryId: "chaat", type: "dish", name: id === "pani-puri" ? "Pani Puri" : `Dish ${id}`, description: "", portion: "8 pcs", price: 50, image: null, available: true, isNew: false, archived: false, webCompatible: true, tags: [], order: 1, bundleGroups: [], ...overrides });
const config: RuntimeConfig = { site: { brandName: "Gruhswad", tagline: "Taste of Home", mobile: "8123415647", orderCutoff: "Order before 9 PM" }, operations: { open: true, message: "", pickupEnabled: true, deliveryEnabled: false }, announcement: { enabled: false, title: "", message: "", linkLabel: "", linkUrl: "", startsAt: null, endsAt: null }, serviceArea: { pickupCities: ["Bengaluru"], pickupState: "Karnataka", pickupCountry: "India", kitchenPlaceId: "", kitchenLatitude: null, kitchenLongitude: null, deliveryRadiusKm: 5 }, orderingPlatforms: [], publicLocation: { enabled: false, name: "", address: "", mapQuery: "", googleMapsUrl: "", directions: "" } };
const publication = (ids: string[], featuredItemId: string | null = ids[0] ?? null): Publication => ({ date: "2026-07-25", published: true, title: "Today's <Fresh> Menu", itemIds: ids, featuredItemId, orderCutoff: "Order by 9:00 PM" });
const build = (pub: Publication, items: CatalogItem[], logoUrl?: string) => buildOneDayMenuPdfDocument({ publication: pub, categories, items, config, qrDataUrl: "data:image/png;base64,QR", logoUrl, now:new Date("2026-07-24T12:00:00Z") });

describe("one-day menu PDF document", () => {
  it("renders saved publication copy, categories, featured item, contact, and QR", () => { const result=build(publication(["pani-puri"]),[item("pani-puri")],"file:///logo.png");expect(result.html).toContain("Today&#39;s &lt;Fresh&gt; Menu");expect(result.html).toContain("25 July 2026");expect(result.html).toContain("TODAY'S SPECIAL");expect(result.html).toContain("Pani Puri");expect(result.html).toContain("8123415647");expect(result.html).toContain("data:image/png;base64,QR");expect(result.html).toContain("file:///logo.png"); });
  it("preserves publication item order inside category order", () => { const result=build(publication(["second","first"],null),[item("first"),item("second")]);expect(result.html.indexOf("Dish second")).toBeLessThan(result.html.indexOf("Dish first")); });
  it("omits stale, unavailable, archived, incompatible, and inactive-category items", () => { const items=[item("valid"),item("missing-status",{available:false}),item("archived",{archived:true}),item("desktop",{webCompatible:false}),item("inactive",{categoryId:"hidden"})];const result=build(publication(items.map((value)=>value.id),"archived"),items);expect(result.omittedItemCount).toBe(4);expect(result.html).not.toContain("TODAY'S SPECIAL");expect(result.html).toContain("Dish valid"); });
  it("collapses the special panel and uses a text wordmark when optional data is absent", () => { const result=build(publication(["plain"],null),[item("plain")]);expect(result.html).not.toContain("TODAY'S SPECIAL");expect(result.html).toContain("class=\"wordmark\">Gruhswad"); });
  it("rejects publications with no printable items", () => expect(()=>build(publication(["gone"]),[])).toThrow("no printable items"));
  it("creates continuation pages for an oversized saved menu", () => { const items=Array.from({length:50},(_,index)=>item(`item-${index}`));const result=build(publication(items.map((value)=>value.id),null),items);expect(result.pageCount).toBeGreaterThan(1);expect(result.html).toContain("class=\"page continuation\"");expect(result.html).toContain(`1 / ${result.pageCount}`); });
});
