import {describe,expect,it} from "vitest";
import {baseQuantity,countTiffinServices,enquiryRequestedQuantity,enquiryWeekdays,nextTiffinPeriod,weightedAverage,youtubeEmbedUrl,youtubeVideoId} from "../src/shared/service-operations";
import {orderInputSchema} from "../src/shared/contracts";

describe("recipe videos",()=>{it("accepts supported YouTube links",()=>{expect(youtubeVideoId("https://youtu.be/dQw4w9WgXcQ")).toBe("dQw4w9WgXcQ");expect(youtubeVideoId("https://www.youtube.com/watch?v=dQw4w9WgXcQ&list=x")).toBe("dQw4w9WgXcQ");expect(youtubeVideoId("https://youtube.com/shorts/dQw4w9WgXcQ")).toBe("dQw4w9WgXcQ");expect(youtubeEmbedUrl("dQw4w9WgXcQ")).toContain("youtube-nocookie.com")});it("rejects unsafe or malformed links",()=>{expect(youtubeVideoId("javascript:alert(1)")).toBeNull();expect(youtubeVideoId("https://example.com/watch?v=dQw4w9WgXcQ")).toBeNull();expect(youtubeVideoId("https://youtube.com/playlist?list=x")).toBeNull()})});
describe("inventory math",()=>{it("converts purchase units and averages cost",()=>{expect(baseQuantity(2,"kg",1,"g")).toBe(2000);expect(baseQuantity(3,"pack",250,"g")).toBe(750);expect(weightedAverage(1000,.1,1000,300)).toBe(.2)});it("rejects incompatible units",()=>expect(()=>baseQuantity(1,"l",1,"g")).toThrow())});
describe("tiffin cycles",()=>{it("builds weekly periods and counts slots",()=>{expect(nextTiffinPeriod("2026-08-16","weekly")).toEqual({start:"2026-08-16",end:"2026-08-22",next:"2026-08-23"});expect(countTiffinServices("2026-08-16","2026-08-22",[1,2,3,4,5],["lunch","dinner"],2)).toBe(20)});it("clamps monthly anniversary periods",()=>expect(nextTiffinPeriod("2026-01-31","monthly")).toEqual({start:"2026-01-31",end:"2026-02-27",next:"2026-02-28"}))});
describe("enquiry conversion defaults",()=>{it("uses the larger guest count or quantity note for every selected line",()=>{expect(enquiryRequestedQuantity({guestCount:25,quantityNotes:"30 servings for each selected dish"})).toBe(30);expect(enquiryRequestedQuantity({guestCount:40,quantityNotes:"30"})).toBe(40)});it("uses people and optional quantity notes for Tiffin defaults",()=>expect(enquiryRequestedQuantity({peopleCount:2,quantityNotes:"3 meals"})).toBe(3));it("normalizes common Tiffin frequency descriptions",()=>{expect(enquiryWeekdays("Monday-Friday")).toEqual([1,2,3,4,5]);expect(enquiryWeekdays("Monday, Wednesday and Saturday")).toEqual([1,3,6]);expect(enquiryWeekdays("daily")).toEqual([0,1,2,3,4,5,6])})});
describe("manual service orders",()=>{const base={customer:{name:"Amol Pandhare",phone:"9663320853",email:"",archived:false},serviceDate:"2026-08-24",fulfilment:"pickup" as const,address:"",notes:"",source:{id:"direct",name:"Direct order"},status:"confirmed" as const,lines:[{name:"Quoted meal",quantity:30,unitPrice:200,consumptionMode:"none" as const}]};it("requires structured guest count for Party and Bulk",()=>{expect(()=>orderInputSchema.parse({...base,serviceType:"party",serviceDetails:{occasion:"Birthday",guestCount:null,dietary:"",packaging:""}})).toThrow(/guest or meal count/i);expect(orderInputSchema.parse({...base,serviceType:"bulk",serviceDetails:{occasion:"Office lunch",guestCount:30,dietary:"No onion",packaging:"Individual boxes"}}).serviceType).toBe("bulk")});it("keeps general orders backward compatible",()=>expect(orderInputSchema.parse({...base,serviceType:"general"}).serviceDetails.guestCount).toBeNull())});
