import { contextBridge, ipcRenderer } from "electron";
import type { AdminApi } from "../shared/contracts";

const api:AdminApi={
  dashboard:(range)=>ipcRenderer.invoke("dashboard",range),
  orders:{list:(range)=>ipcRenderer.invoke("orders:list",range),listUnified:(query)=>ipcRenderer.invoke("orders:unified",query),detail:(kind,id)=>ipcRenderer.invoke("orders:detail",kind,id),sources:()=>ipcRenderer.invoke("orders:sources"),save:(input)=>ipcRenderer.invoke("orders:save",input),updateStatus:(id,status)=>ipcRenderer.invoke("orders:status",id,status),addPayment:(input)=>ipcRenderer.invoke("orders:payment",input)},
  customers:{list:(query,includeArchived)=>ipcRenderer.invoke("customers:list",query,includeArchived),save:(input)=>ipcRenderer.invoke("customers:save",input),archive:(id,archived)=>ipcRenderer.invoke("customers:archive",id,archived),openWhatsApp:(id)=>ipcRenderer.invoke("customers:whatsapp",id),composeEmail:(id)=>ipcRenderer.invoke("customers:email",id)},
  expenses:{list:(range)=>ipcRenderer.invoke("expenses:list",range),save:(input)=>ipcRenderer.invoke("expenses:save",input),remove:(id)=>ipcRenderer.invoke("expenses:remove",id)},
  catalog:{get:()=>ipcRenderer.invoke("catalog:get"),save:(input)=>ipcRenderer.invoke("catalog:save",input),saveWithImage:(input,selection)=>ipcRenderer.invoke("catalog:save-with-image",input,selection),imageAssets:()=>ipcRenderer.invoke("catalog:image-assets"),chooseImage:()=>ipcRenderer.invoke("catalog:choose-image"),archive:(id,archived)=>ipcRenderer.invoke("catalog:archive",id,archived),saveCategory:(input)=>ipcRenderer.invoke("catalog:category-save",input),setCategoryActive:(id,active)=>ipcRenderer.invoke("catalog:category-active",id,active),exportPdf:()=>ipcRenderer.invoke("catalog:export-pdf"),exportImages:()=>ipcRenderer.invoke("catalog:export-images"),previewImages:()=>ipcRenderer.invoke("catalog:preview-images")},
  operations:{get:()=>ipcRenderer.invoke("operations:get"),save:(input)=>ipcRenderer.invoke("operations:save",input)},
  menu:{catalog:()=>ipcRenderer.invoke("menu:catalog"),history:()=>ipcRenderer.invoke("menu:history"),getCurrent:()=>ipcRenderer.invoke("menu:current"),publish:(input)=>ipcRenderer.invoke("menu:publish",input),exportPdf:()=>ipcRenderer.invoke("menu:export-pdf"),exportPhotoPdf:()=>ipcRenderer.invoke("menu:export-photo-pdf"),exportImages:()=>ipcRenderer.invoke("menu:export-images"),previewImages:()=>ipcRenderer.invoke("menu:preview-images"),shareWhatsApp:()=>ipcRenderer.invoke("menu:share-whatsapp")},
  images:{preview:(index)=>ipcRenderer.invoke("images:preview",index),open:(index)=>ipcRenderer.invoke("images:open",index),showInFolder:(index)=>ipcRenderer.invoke("images:show-in-folder",index)},
  cloudOrders:{list:(query)=>ipcRenderer.invoke("cloud-orders:list",query),detail:(id)=>ipcRenderer.invoke("cloud-orders:detail",id),updateStatus:(id,status)=>ipcRenderer.invoke("cloud-orders:status",id,status)},
  sync:{status:()=>ipcRenderer.invoke("sync:status"),attention:()=>ipcRenderer.invoke("sync:attention"),previewPull:()=>ipcRenderer.invoke("sync:preview-pull"),pull:()=>ipcRenderer.invoke("sync:pull"),previewPush:()=>ipcRenderer.invoke("sync:preview-push"),push:()=>ipcRenderer.invoke("sync:push"),conflicts:()=>ipcRenderer.invoke("sync:conflicts"),resolve:(id,resolution)=>ipcRenderer.invoke("sync:resolve",id,resolution),history:()=>ipcRenderer.invoke("sync:history"),onStartupPullComplete:(callback)=>{const handler=()=>callback();ipcRenderer.on("sync:startup-pull-complete",handler);return()=>ipcRenderer.removeListener("sync:startup-pull-complete",handler)},onStartupPullSettled:(callback)=>{const handler=()=>callback();ipcRenderer.on("sync:startup-pull-settled",handler);return()=>ipcRenderer.removeListener("sync:startup-pull-settled",handler)},onNavigateToSync:(callback)=>{const handler=()=>callback();ipcRenderer.on("sync:navigate",handler);return()=>ipcRenderer.removeListener("sync:navigate",handler)}},
  menuPublishing:{status:()=>ipcRenderer.invoke("menu-publishing:status"),publish:()=>ipcRenderer.invoke("menu-publishing:publish")},
  external:{openAlphaInitiatives:()=>ipcRenderer.invoke("external:open-alpha-initiatives")},
  reports:{exportCsv:(kind,range)=>ipcRenderer.invoke("reports:export",kind,range)}, inbox:{list:()=>ipcRenderer.invoke("inbox:list"),sync:()=>ipcRenderer.invoke("inbox:sync"),createOrder:()=>Promise.reject(new Error("Open the parsed draft and save it from Orders."))},
  settings:{get:()=>ipcRenderer.invoke("settings:get"),set:(values,secrets)=>ipcRenderer.invoke("settings:set",values,secrets),importGcsCredentials:()=>ipcRenderer.invoke("settings:import-gcs"),backup:()=>ipcRenderer.invoke("settings:backup"),restore:()=>ipcRenderer.invoke("settings:restore")},
  enquiries:{list:(input)=>ipcRenderer.invoke("enquiries:list",input),detail:(id)=>ipcRenderer.invoke("enquiries:detail",id),count:()=>ipcRenderer.invoke("enquiries:count"),updateStatus:(id,status)=>ipcRenderer.invoke("enquiries:status",id,status),preference:()=>ipcRenderer.invoke("enquiries:preference"),setPreference:(enabled)=>ipcRenderer.invoke("enquiries:set-preference",enabled),openWhatsApp:(id)=>ipcRenderer.invoke("enquiries:whatsapp",id),composeEmail:(id)=>ipcRenderer.invoke("enquiries:email",id),call:(id)=>ipcRenderer.invoke("enquiries:call",id),copyReference:(id)=>ipcRenderer.invoke("enquiries:copy",id),onOpen:(callback)=>{const handler=(_event:unknown,detail:any)=>callback(detail);ipcRenderer.on("enquiries:open",handler);return()=>ipcRenderer.removeListener("enquiries:open",handler)}},
  updates:{check:()=>ipcRenderer.invoke("updates:check"),install:()=>ipcRenderer.invoke("updates:install"),onStatus:(callback)=>{const handler=(_e:unknown,status:string)=>callback(status);ipcRenderer.on("updates:status",handler);return()=>ipcRenderer.removeListener("updates:status",handler)}},
};
contextBridge.exposeInMainWorld("admin",api);
