import { z } from "zod";
import type { DatabaseConnectionInfo } from "./environment";
import type { PushSectionCounts } from "./push-policy";

export const dateSchema = z.string().regex(/^\d{4}-\d{2}-\d{2}$/);
export const fulfilmentSchema = z.enum(["delivery", "pickup"]);
export const orderStatusSchema = z.enum(["draft", "confirmed", "preparing", "ready", "completed", "cancelled"]);
export const cloudOrderStatusSchema = z.enum(["handoff_created", "customer_confirmed_sent", "confirmed", "preparing", "ready", "completed", "cancelled"]);
export const orderLineSchema = z.object({ menuItemId: z.string().nullable().optional(), name: z.string().min(1), quantity: z.number().int().min(1).max(1000), unitPrice: z.number().nonnegative() });
export const orderInputSchema = z.object({ id: z.string().optional(), customerName: z.string().min(2), phone: z.string().min(8), serviceDate: dateSchema, fulfilment: fulfilmentSchema, address: z.string().default(""), notes: z.string().default(""), source: z.enum(["manual", "whatsapp", "phone", "walk-in"]).default("manual"), status: orderStatusSchema.default("draft"), lines: z.array(orderLineSchema).min(1) });
export const expenseInputSchema = z.object({ id: z.string().optional(), date: dateSchema, category: z.string().min(1), description: z.string().min(1), amount: z.number().positive(), paymentMethod: z.string().min(1), notes: z.string().default("") });
export const paymentInputSchema = z.object({ orderId: z.string(), amount: z.number().positive(), receivedAt: z.string().min(10), method: z.string().min(1), status: z.enum(["received", "refunded"]).default("received") });

export const bundleChoiceSchema = z.object({ id: z.string().regex(/^[a-z0-9-]+$/), itemId: z.string(), name: z.string().default(""), upgradePrice: z.number().nonnegative(), available: z.boolean(), order: z.number().int().nonnegative() });
export const bundleGroupSchema = z.object({ id: z.string().regex(/^[a-z0-9-]+$/), name: z.string().min(1), minChoices: z.number().int().nonnegative(), maxChoices: z.number().int().nonnegative(), order: z.number().int().nonnegative(), choices: z.array(bundleChoiceSchema) }).superRefine((group, ctx) => { if (group.maxChoices < group.minChoices || group.maxChoices > group.choices.length) ctx.addIssue({ code: "custom", message: "Choice limits do not match the available choices." }); });
export const catalogCategorySchema = z.object({ id: z.string().regex(/^[a-z0-9-]+$/), name: z.string().trim().min(1), order: z.number().int().nonnegative(), active: z.boolean() });
export const catalogImageSchema = z.string().trim().regex(/^[^\\/:*?"<>|]+\.(?:avif|gif|jpe?g|png|webp)$/i, "Use a local image asset filename such as dish.jpg.").nullable().optional();
export const catalogItemSchema = z.object({ id: z.string().regex(/^[a-z0-9-]+$/), categoryId: z.string().min(1), type: z.enum(["dish", "combo", "thali"]), name: z.string().trim().min(1), description: z.string().default(""), portion: z.string().default(""), price: z.number().nonnegative(), image: catalogImageSchema, available: z.boolean(), isNew: z.boolean(), archived: z.boolean(), webCompatible: z.boolean().default(true), tags: z.array(z.string()).default([]), order: z.number().int().nonnegative(), bundleGroups: z.array(bundleGroupSchema).default([]) });
export const siteSchema = z.object({ brandName: z.string().min(1), tagline: z.string(), mobile: z.string().regex(/^\d{10}$/), orderCutoff: z.string().min(1) });
export const preorderWindowSchema = z.object({ start: z.string().regex(/^(?:[01]\d|2[0-3]):[0-5]\d$/), end: z.string().regex(/^(?:[01]\d|2[0-3]):[0-5]\d$/) }).refine((value)=>value.start<value.end,{message:"The preorder end time must be later than the start time."});
export const operationsSchema = z.object({ open: z.boolean(), message: z.string(), pickupEnabled: z.boolean(), deliveryEnabled: z.boolean(), preorderWindow: preorderWindowSchema.default({start:"00:00",end:"21:00"}) });
export const announcementSchema = z.object({ enabled: z.boolean(), title: z.string().trim().max(80), message: z.string().trim().max(280), linkLabel: z.string().trim().max(40), linkUrl: z.string().trim(), startsAt: z.string().datetime({ offset: true }).nullable(), endsAt: z.string().datetime({ offset: true }).nullable() }).superRefine((value,ctx)=>{if(value.enabled&&!value.message)ctx.addIssue({code:"custom",path:["message"],message:"Enter an announcement message before showing it."});if(value.startsAt&&value.endsAt&&Date.parse(value.startsAt)>=Date.parse(value.endsAt))ctx.addIssue({code:"custom",path:["endsAt"],message:"The announcement end must be after its start."});if(Boolean(value.linkLabel)!==Boolean(value.linkUrl))ctx.addIssue({code:"custom",path:[value.linkLabel?"linkUrl":"linkLabel"],message:"Provide both a link label and URL, or leave both blank."});if(value.linkUrl){try{if(new URL(value.linkUrl).protocol!=="https:")throw new Error();}catch{ctx.addIssue({code:"custom",path:["linkUrl"],message:"The announcement link must be a secure HTTPS URL."});}}});
export const serviceAreaSchema = z.object({ pickupCities: z.array(z.string()), pickupState: z.string(), pickupCountry: z.string(), kitchenPlaceId: z.string(), kitchenLatitude: z.number().nullable(), kitchenLongitude: z.number().nullable(), deliveryRadiusKm: z.number().positive() });
export const orderingPlatformSchema = z.object({ id: z.string().regex(/^[a-z0-9-]+$/), name: z.string().min(1), description: z.string(), url: z.string(), status: z.enum(["available", "coming-soon", "hidden"]), order: z.number().int().nonnegative() });
export const publicLocationSchema = z.object({ enabled: z.boolean(), name: z.string(), address: z.string(), mapQuery: z.string(), googleMapsUrl: z.string(), directions: z.string() });
export const runtimeConfigSchema = z.object({ site: siteSchema, operations: operationsSchema, announcement: announcementSchema, serviceArea: serviceAreaSchema, orderingPlatforms: z.array(orderingPlatformSchema), publicLocation: publicLocationSchema });
export const publicationSchema = z.object({ mode: z.enum(["one-day", "weekly"]).default("one-day"), date: dateSchema, weeklyStartDate: dateSchema.nullable().default(null), published: z.boolean(), title: z.string().min(1), itemIds: z.array(z.string()).min(1), featuredItemId: z.string().nullable(), orderCutoff: z.string().min(1) }).superRefine((data, ctx) => { if (new Set(data.itemIds).size !== data.itemIds.length) ctx.addIssue({ code: "custom", message: "Duplicate menu items are not allowed." }); if (data.featuredItemId && !data.itemIds.includes(data.featuredItemId)) ctx.addIssue({ code: "custom", message: "Featured item must be selected." }); if (data.mode === "weekly" && !data.weeklyStartDate) ctx.addIssue({ code: "custom", path: ["weeklyStartDate"], message: "Choose the weekly menu activation date." }); });

export type OrderInput = z.infer<typeof orderInputSchema>;
export type ExpenseInput = z.infer<typeof expenseInputSchema>;
export type PaymentInput = z.infer<typeof paymentInputSchema>;
export type CatalogItem = z.infer<typeof catalogItemSchema>;
export type CatalogCategory = z.infer<typeof catalogCategorySchema>;
export type RuntimeConfig = z.input<typeof runtimeConfigSchema>;
export type Publication = z.input<typeof publicationSchema>;
export type DateRange = { from: string; to: string };
export type Dashboard = { revenue: number; expenses: number; profit: number; orderCount: number; outstanding: number; averageOrder: number; recentOrders: Record<string, unknown>[]; expenseByCategory: { category: string; total: number }[] };
export type SyncPreview = { inserts: number; updates: number; conflicts: number; dirty: number; entities: { type: string; id: string; action: string }[] };
export type PushPreview = SyncPreview & { pushableDirty: number; excludedDirty: number; sections: PushSectionCounts };
export type SyncStatus = { online: boolean; dirty: number; conflicts: number; lastPull: string | null; lastPush: string | null; runs: any[]; connection: DatabaseConnectionInfo };
export type SyncAttentionStatus = { conflicts: number; pushableDirty: number; requiresAttention: boolean };
export type MenuPdfExportResult = { canceled: boolean; path: string | null; pageCount: number; warning: string | null };
export type MenuImageExportResult = { canceled: boolean; paths: string[]; imageCount: number; warning: string | null };
export type MenuType = "master" | "one-day";
export type MenuImagePublicationStatus = { configured: boolean; bucket: string; ready: boolean; local: Record<MenuType, { state: string; generatedAt: string | null; pageCount: number; files: string[] }>; cloud: Record<MenuType, { generatedAt: string; publishedAt: string; pageCount: number } | null>; error: string | null };
export type MenuImagePublishResult = { publishedAt: string; bucket: string; menus: Record<MenuType, { action: "uploaded" | "unchanged"; objects: string[] }>; warnings: string[] };
export type CatalogImageAsset = { filename: string; source: "packaged"; previewUrl: string };
export type CatalogImageSelection = { canceled: boolean; token: string | null; originalName: string | null; format: "jpg" | "png" | "webp" | null; previewDataUrl: string | null };
export type CatalogImageSaveSelection = { kind: "unchanged" } | { kind: "placeholder" } | { kind: "asset"; filename: string } | { kind: "browse"; token: string };

export type AdminApi = {
  dashboard(range: DateRange): Promise<Dashboard>;
  orders: { list(range?: DateRange): Promise<any[]>; save(input: OrderInput): Promise<string>; updateStatus(id: string, status: z.infer<typeof orderStatusSchema>): Promise<void>; addPayment(input: PaymentInput): Promise<void> };
  expenses: { list(range?: DateRange): Promise<any[]>; save(input: ExpenseInput): Promise<string>; remove(id: string): Promise<void> };
  catalog: { get(): Promise<{ categories: CatalogCategory[]; items: CatalogItem[] }>; save(item: CatalogItem): Promise<void>; saveWithImage(item: CatalogItem, selection: CatalogImageSaveSelection): Promise<{ item: CatalogItem; warning: string | null }>; imageAssets(): Promise<CatalogImageAsset[]>; chooseImage(): Promise<CatalogImageSelection>; archive(id: string, archived: boolean): Promise<void>; saveCategory(category: CatalogCategory): Promise<void>; setCategoryActive(id: string, active: boolean): Promise<void>; exportPdf(): Promise<MenuPdfExportResult>; exportImages(): Promise<MenuImageExportResult>; previewImages(): Promise<MenuImageExportResult> };
  operations: { get(): Promise<RuntimeConfig>; save(input: RuntimeConfig): Promise<void> };
  menu: { catalog(): Promise<{ categories: CatalogCategory[]; items: CatalogItem[] }>; history(): Promise<any[]>; getCurrent(): Promise<Publication | null>; publish(input: Publication): Promise<void>; exportPdf(): Promise<MenuPdfExportResult>; exportPhotoPdf(): Promise<MenuPdfExportResult>; exportImages(): Promise<MenuImageExportResult>; previewImages(): Promise<MenuImageExportResult>; shareWhatsApp(): Promise<void> };
  images: { preview(index: number): Promise<string>; open(index: number): Promise<void>; showInFolder(index: number): Promise<void> };
  cloudOrders: { list(query?: string): Promise<any[]>; detail(id: string): Promise<any>; updateStatus(id: string, status: z.infer<typeof cloudOrderStatusSchema>): Promise<void> };
  sync: { status(): Promise<SyncStatus>; attention(): Promise<SyncAttentionStatus>; previewPull(): Promise<SyncPreview>; pull(): Promise<SyncPreview>; previewPush(): Promise<PushPreview>; push(): Promise<PushPreview>; conflicts(): Promise<any[]>; resolve(id: string, resolution: "local" | "neon"): Promise<void>; history(): Promise<any[]>; onStartupPullComplete(callback: () => void): () => void; onStartupPullSettled(callback: () => void): () => void; onNavigateToSync(callback: () => void): () => void };
  menuPublishing: { status(): Promise<MenuImagePublicationStatus>; publish(): Promise<MenuImagePublishResult> };
  external: { openAlphaInitiatives(): Promise<void> };
  reports: { exportCsv(kind: "orders" | "expenses" | "summary", range: DateRange): Promise<string | null> };
  inbox: { list(): Promise<any[]>; sync(): Promise<{ imported: number; unmatched: number }>; createOrder(importId: string): Promise<string> };
  settings: { get(): Promise<Record<string, string | boolean>>; set(values: Record<string, string>, secrets?: Record<string, string>): Promise<void>; importGcsCredentials(): Promise<{ canceled: boolean; configured: boolean }>; backup(): Promise<string | null>; restore(): Promise<boolean> };
  updates: { check(): Promise<void>; install(): Promise<void>; onStatus(callback: (status: string) => void): () => void };
};
