import { runtimeConfigSchema, type RuntimeConfig } from "./contracts";

export const runtimeDefaults:RuntimeConfig={site:{brandName:"Gruhswad",tagline:"Taste of Home",mobile:"8123415647",orderCutoff:"Order before 9:00 PM for next-day delivery"},operations:{open:true,message:"",pickupEnabled:true,deliveryEnabled:false,maxPartyBulkGuests:25,preorderWindow:{start:"00:00",end:"21:00"},closurePeriod:null},announcements:{maxAnnouncements:6,items:[]},serviceArea:{pickupCities:["Bengaluru"],pickupState:"Karnataka",pickupCountry:"India",kitchenPlaceId:"",kitchenLatitude:null,kitchenLongitude:null,deliveryRadiusKm:5},orderingPlatforms:[],publicLocation:{enabled:false,name:"",address:"",mapQuery:"",googleMapsUrl:"",directions:""}};
function normalizedMobile(value:unknown){const digits=String(value??"").replace(/\D/g,"");return digits.length>=10?digits.slice(-10):runtimeDefaults.site.mobile;}
export function normalizeRuntimeSetting(key:string,payload:any){
  if(key==="site"){const value=payload&&typeof payload==="object"?payload:{};return{...runtimeDefaults.site,...value,mobile:normalizedMobile(value.mobile??value.displayPhone??value.whatsapp)};}
  if(key==="operations"){const value=payload&&typeof payload==="object"?payload:{};const candidate={...runtimeDefaults.operations,...value,preorderWindow:{...runtimeDefaults.operations.preorderWindow,...(value.preorderWindow&&typeof value.preorderWindow==="object"?value.preorderWindow:{})}};const parsed=runtimeConfigSchema.shape.operations.safeParse(candidate);return parsed.success?parsed.data:{...runtimeDefaults.operations,open:Boolean(value.open),message:String(value.message??""),pickupEnabled:Boolean(value.pickupEnabled),deliveryEnabled:Boolean(value.deliveryEnabled)};}
  if(key==="announcement"){const input=payload&&typeof payload==="object"?payload as any:{};const max=Number.isInteger(Number(input.maxAnnouncements))&&Number(input.maxAnnouncements)>=1&&Number(input.maxAnnouncements)<=6?Number(input.maxAnnouncements):6;const raw=Array.isArray(input.items)?input.items:("enabled" in input?[input]:[]);const items=raw.map((item:any,index:number)=>({...item,id:typeof item.id==="string"&&/^[a-z0-9-]+$/.test(item.id)?item.id:`announcement-legacy-${index+1}`,theme:["saffron","rose","leaf","plum","cocoa","sunrise"].includes(item.theme)?item.theme:"cocoa",enabled:index<max?Boolean(item.enabled):false}));const parsed=runtimeConfigSchema.shape.announcements.safeParse({maxAnnouncements:max,items});return parsed.success?parsed.data:runtimeDefaults.announcements;}
  if(key==="service_area")return{...runtimeDefaults.serviceArea,...(payload&&typeof payload==="object"?payload:{})};
  if(key==="ordering_platforms")return Array.isArray(payload)?payload:runtimeDefaults.orderingPlatforms;
  if(key==="public_location")return{...runtimeDefaults.publicLocation,...(payload&&typeof payload==="object"?payload:{})};
  return payload;
}
export function runtimeConfigFromSettings(map:Record<string,unknown>):RuntimeConfig{return runtimeConfigSchema.parse({site:normalizeRuntimeSetting("site",map.site),operations:normalizeRuntimeSetting("operations",map.operations),announcements:normalizeRuntimeSetting("announcement",map.announcement),serviceArea:normalizeRuntimeSetting("service_area",map.service_area),orderingPlatforms:normalizeRuntimeSetting("ordering_platforms",map.ordering_platforms),publicLocation:normalizeRuntimeSetting("public_location",map.public_location)});}
