import { randomUUID } from "node:crypto";
import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import Database from "better-sqlite3";
import { drizzle } from "drizzle-orm/better-sqlite3";
import seed from "../shared/master-menu.seed.json";
import { orderInputSchema, publicationSchema, runtimeConfigSchema, type CatalogCategory, type CatalogItem, type CustomerInput, type CustomerSummary, type DateRange, type ExpenseInput, type OrderInput, type OrderingSource, type PaymentInput, type Publication, type RuntimeConfig, type UnifiedOrderDetail, type UnifiedOrderQuery, type UnifiedOrderSummary } from "../shared/contracts";
import { isPublishableItem } from "../shared/catalog";
import { normalizeCustomerInput } from "../shared/customers";
import { normalizeServiceDate, normalizeTimestamp } from "../shared/dates";
import { normalizeCloudOrderLine } from "../shared/order-detail";
import { normalizeRuntimeSetting, runtimeConfigFromSettings } from "../shared/runtime-config";
import * as schema from "./schema";

let sqlite: Database.Database;
export let db: ReturnType<typeof drizzle<typeof schema>>;

function repairCloudOrderDates(){const rows=sqlite.prepare("SELECT id,service_date,created_at,updated_at FROM cloud_orders").all() as {id:string;service_date:string;created_at:string;updated_at:string}[];const update=sqlite.prepare("UPDATE cloud_orders SET service_date=?,created_at=?,updated_at=? WHERE id=?");sqlite.transaction(()=>{for(const row of rows)update.run(normalizeServiceDate(row.service_date),normalizeTimestamp(row.created_at),normalizeTimestamp(row.updated_at),row.id);})();}

export function initializeDatabase(databasePath: string, migrationPath: string) {
  sqlite = new Database(databasePath);
  sqlite.pragma("journal_mode = WAL"); sqlite.pragma("foreign_keys = ON");
  sqlite.exec("CREATE TABLE IF NOT EXISTS schema_migrations (version TEXT PRIMARY KEY, applied_at TEXT NOT NULL)");
  const applied = new Set((sqlite.prepare("SELECT version FROM schema_migrations").all() as { version: string }[]).map((row) => row.version));
  for (const file of readdirSync(migrationPath).filter((name) => name.endsWith(".sql")).sort()) {
    const version = file.replace(/\.sql$/, "");
    if (applied.has(version)) continue;
    const migration = readFileSync(join(migrationPath, file), "utf8");
    sqlite.transaction(() => {
      sqlite.exec(migration);
      sqlite.prepare("INSERT INTO schema_migrations(version, applied_at) VALUES (?, ?)").run(version, new Date().toISOString());
    })();
  }
  repairCloudOrderDates();
  seedCatalog(); repairRuntimeSettings(); db = drizzle(sqlite, { schema });
}

function seedCatalog() {
  const category = sqlite.prepare("INSERT OR IGNORE INTO menu_categories(id,name,sort_order) VALUES (@id,@name,@order)");
  const item = sqlite.prepare("INSERT OR IGNORE INTO menu_items(id,category_id,name,description,portion,price,image,available,web_compatible) VALUES (@id,@categoryId,@name,@description,@portion,@price,@image,@available,1)");
  sqlite.transaction(() => { for (const value of seed.categories) category.run(value); for (const value of seed.items) item.run({ ...value, image: value.image ?? null, available: value.available ? 1 : 0 }); })();
}

export function getCatalog() {
  const categories = (sqlite.prepare("SELECT id,name,sort_order AS 'order',active,updated_at AS updatedAt FROM menu_categories ORDER BY sort_order").all() as any[])
    .map((category) => ({ ...category, active: Boolean(category.active) }));
  const groups = sqlite.prepare("SELECT * FROM bundle_option_groups ORDER BY display_order").all() as any[];
  const choices = sqlite.prepare("SELECT c.*,i.name FROM bundle_option_choices c LEFT JOIN menu_items i ON i.id=c.item_id ORDER BY c.display_order").all() as any[];
  const items = (sqlite.prepare("SELECT id,category_id AS categoryId,item_type AS type,name,description,portion,price,image,available,is_new AS isNew,tags,display_order AS 'order',archived_at AS archivedAt,web_compatible AS webCompatible,updated_at AS updatedAt FROM menu_items ORDER BY display_order,name").all() as any[]).map((item) => ({ ...item, available: Boolean(item.available), isNew: Boolean(item.isNew), archived: Boolean(item.archivedAt), webCompatible: Boolean(item.webCompatible), tags: JSON.parse(item.tags || "[]"), bundleGroups: groups.filter((group) => group.item_id === item.id).map((group) => ({ id: group.id, name: group.name, minChoices: group.min_choices, maxChoices: group.max_choices, order: group.display_order, choices: choices.filter((choice) => choice.group_id === group.id).map((choice) => ({ id: choice.id, itemId: choice.item_id, name: choice.name || "", upgradePrice: choice.upgrade_price, available: Boolean(choice.available), order: choice.display_order })) })) }));
  return { categories, items };
}
export function listOrders(range?:DateRange){const where=range?"WHERE o.service_date BETWEEN ? AND ?":"";return sqlite.prepare(`SELECT o.*,c.name customer_name,c.phone,COALESCE((SELECT SUM(CASE WHEN direction='received' THEN amount ELSE -amount END) FROM unified_payments WHERE order_kind='local' AND order_id=o.id),0) paid FROM orders o JOIN customers c ON c.id=o.customer_id ${where} ORDER BY o.service_date DESC,o.created_at DESC`).all(...(range?[range.from,range.to]:[]));}
export function listExpenses(range?: DateRange) { return range ? sqlite.prepare("SELECT * FROM expenses WHERE date BETWEEN ? AND ? ORDER BY date DESC").all(range.from, range.to) : sqlite.prepare("SELECT * FROM expenses ORDER BY date DESC").all(); }

function saveCustomerRecord(input:CustomerInput,markForSync=true){
  const value=normalizeCustomerInput(input),now=new Date().toISOString();
  const existingCloud=(value.id?sqlite.prepare("SELECT id,name,phone_e164,email,archived_at,created_at,updated_at FROM cloud_customers WHERE id=?").get(value.id):sqlite.prepare("SELECT id,name,phone_e164,email,archived_at,created_at,updated_at FROM cloud_customers WHERE phone_e164=?").get(value.phone)) as {id:string;name:string;phone_e164:string;email:string|null;archived_at:string|null;created_at:string;updated_at:string}|undefined;
  const existingLocal=sqlite.prepare("SELECT id,created_at FROM customers WHERE phone=?").get(value.phone) as {id:string;created_at:string}|undefined;
  const id=value.id??existingCloud?.id??existingLocal?.id??randomUUID(),createdAt=existingCloud?.created_at??existingLocal?.created_at??now,archivedAt=value.archived?(existingCloud?.archived_at??now):null;
  const duplicate=sqlite.prepare("SELECT id FROM cloud_customers WHERE phone_e164=? AND id<>?").get(value.phone,id) as {id:string}|undefined;
  if(duplicate)throw new Error("Another customer already uses this phone number.");
  const changed=!existingCloud||existingCloud.name!==value.name||existingCloud.phone_e164!==value.phone||(existingCloud.email??null)!==value.email||Boolean(existingCloud.archived_at)!==value.archived,updatedAt=changed?now:existingCloud.updated_at;
  sqlite.prepare("INSERT INTO cloud_customers(id,firebase_uid,phone_e164,name,email,archived_at,verified_at,created_at,updated_at) VALUES(?,NULL,?,?,?,?,NULL,?,?) ON CONFLICT(id) DO UPDATE SET phone_e164=excluded.phone_e164,name=excluded.name,email=excluded.email,archived_at=excluded.archived_at,updated_at=excluded.updated_at").run(id,value.phone,value.name,value.email,archivedAt,createdAt,updatedAt);
  sqlite.prepare("INSERT INTO customers(id,name,phone,email,address,archived_at,created_at,updated_at) VALUES(?,?,?,?,NULL,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,phone=excluded.phone,email=excluded.email,archived_at=excluded.archived_at,updated_at=excluded.updated_at").run(id,value.name,value.phone,value.email,archivedAt,createdAt,updatedAt);
  if(markForSync&&changed)markDirty("cloud_customer",id,value);
  return id;
}

export function saveCustomer(input:CustomerInput){return sqlite.transaction(()=>saveCustomerRecord(input,true))();}
export function archiveCustomer(id:string,archived:boolean){const row=sqlite.prepare("SELECT id,name,phone_e164 phone,email FROM cloud_customers WHERE id=?").get(id) as any;if(!row)throw new Error("Customer not found.");saveCustomer({...row,email:row.email??"",archived});}
export function customerContact(id:string){const row=sqlite.prepare("SELECT id,name,phone_e164 phone,email FROM cloud_customers WHERE id=?").get(id) as any;if(!row)throw new Error("Customer not found.");return row as {id:string;name:string;phone:string;email:string|null};}
export function listCustomers(query="",includeArchived=false):CustomerSummary[]{
  const term=query.trim().toLowerCase(),states=new Map((sqlite.prepare("SELECT entity_id,dirty,remote_version FROM sync_state WHERE entity_type='cloud_customer'").all() as any[]).map((row)=>[row.entity_id,row]));
  const addresses=sqlite.prepare("SELECT customer_id,formatted_address FROM cloud_customer_addresses ORDER BY is_default DESC,created_at").all() as any[];
  return (sqlite.prepare("SELECT id,name,phone_e164 phone,email,archived_at,created_at,updated_at FROM cloud_customers ORDER BY name COLLATE NOCASE").all() as any[])
    .filter((row)=>includeArchived||!row.archived_at).filter((row)=>!term||`${row.name} ${row.phone} ${row.email??""}`.toLowerCase().includes(term))
    .map((row)=>({id:row.id,name:row.name,phone:row.phone,email:row.email??null,archived:Boolean(row.archived_at),source:states.get(row.id)?.dirty&&!states.get(row.id)?.remote_version?"local":"neon",createdAt:row.created_at,updatedAt:row.updated_at,addresses:addresses.filter((entry)=>entry.customer_id===row.id).map((entry)=>entry.formatted_address)}));
}

export function saveOrder(rawInput: OrderInput) {
  const input=orderInputSchema.parse(rawInput);
  const id = input.id ?? randomUUID(), now = new Date().toISOString();
  sqlite.transaction(() => {
    const customerId=saveCustomerRecord(input.customer,true);
    const total = input.lines.reduce((sum,line)=>sum+line.quantity*line.unitPrice,0)+input.adjustmentAmount;
    const existing=sqlite.prepare("SELECT order_number,created_at,status FROM orders WHERE id=?").get(id) as {order_number:string;created_at:string;status:string}|undefined;
    const orderNumber=existing?.order_number??`MAN-${id.replace(/-/g,"").slice(0,8).toUpperCase()}`;
    sqlite.prepare("INSERT INTO orders(id,customer_id,service_date,fulfilment,address,notes,source,source_platform_id,source_platform_name,status,payment_status,total,created_at,updated_at,order_number,service_type,service_end_date,service_start_time,service_end_time,enquiry_id,enquiry_reference,tiffin_plan_id,adjustment_label,adjustment_amount,service_details) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET customer_id=excluded.customer_id,service_date=excluded.service_date,fulfilment=excluded.fulfilment,address=excluded.address,notes=excluded.notes,source=excluded.source,source_platform_id=excluded.source_platform_id,source_platform_name=excluded.source_platform_name,status=excluded.status,total=excluded.total,updated_at=excluded.updated_at,service_type=excluded.service_type,service_end_date=excluded.service_end_date,service_start_time=excluded.service_start_time,service_end_time=excluded.service_end_time,enquiry_id=excluded.enquiry_id,enquiry_reference=excluded.enquiry_reference,tiffin_plan_id=excluded.tiffin_plan_id,adjustment_label=excluded.adjustment_label,adjustment_amount=excluded.adjustment_amount,service_details=excluded.service_details").run(id,customerId,input.serviceDate,input.fulfilment,input.address,input.notes,input.source.id,input.source.id,input.source.name,input.status,"unpaid",total,existing?.created_at??now,now,orderNumber,input.serviceType,input.serviceEndDate,input.serviceStartTime,input.serviceEndTime,input.enquiryId??null,input.enquiryReference??null,input.tiffinPlanId??null,input.adjustmentLabel,input.adjustmentAmount,JSON.stringify(input.serviceDetails));
    releaseOrderReservations(id);
    sqlite.prepare("DELETE FROM order_lines WHERE order_id=?").run(id);
    const insert = sqlite.prepare("INSERT INTO order_lines(id,order_id,menu_item_id,name,quantity,unit_price,line_total,recipe_snapshot,consumption_mode) VALUES(?,?,?,?,?,?,?,?,?)");
    for (const line of input.lines){const snapshot=line.consumptionMode==="recipe"&&line.recipeId?recipeSnapshot(line.recipeId):null;insert.run(randomUUID(),id,line.menuItemId??null,line.name,line.quantity,line.unitPrice,line.quantity*line.unitPrice,snapshot?JSON.stringify(snapshot):null,line.consumptionMode);}
    if(input.status==="confirmed")reserveOrder(id);
  })(); return id;
}
function recipeSnapshot(recipeId:string){const recipe=sqlite.prepare("SELECT id,name,version,yield_quantity,youtube_video_id FROM recipes WHERE id=? AND archived_at IS NULL").get(recipeId) as any;if(!recipe)throw new Error("Choose an active recipe.");const ingredients=sqlite.prepare("SELECT ri.stock_item_id stockItemId,s.name,ri.quantity FROM recipe_ingredients ri JOIN stock_items s ON s.id=ri.stock_item_id WHERE ri.recipe_id=?").all(recipeId);return{recipeId:recipe.id,version:recipe.version,name:recipe.name,yieldQuantity:recipe.yield_quantity,youtubeVideoId:recipe.youtube_video_id,ingredients};}
function releaseOrderReservations(orderId:string){const rows=sqlite.prepare("SELECT stock_item_id,quantity FROM stock_reservations WHERE order_id=?").all(orderId) as any[];for(const row of rows)sqlite.prepare("UPDATE stock_items SET reserved=MAX(0,reserved-?),updated_at=? WHERE id=?").run(row.quantity,new Date().toISOString(),row.stock_item_id);sqlite.prepare("DELETE FROM stock_reservations WHERE order_id=?").run(orderId);}
function reserveOrder(orderId:string){const lines=sqlite.prepare("SELECT quantity,recipe_snapshot FROM order_lines WHERE order_id=? AND consumption_mode='recipe'").all(orderId) as any[],needed=new Map<string,{quantity:number;snapshot:string}>();for(const line of lines){const snapshot=JSON.parse(line.recipe_snapshot),scale=line.quantity/Number(snapshot.yieldQuantity||1);for(const ingredient of snapshot.ingredients){const current=needed.get(ingredient.stockItemId)?.quantity??0;needed.set(ingredient.stockItemId,{quantity:current+Number(ingredient.quantity)*scale,snapshot:line.recipe_snapshot});}}const insert=sqlite.prepare("INSERT INTO stock_reservations(id,order_id,stock_item_id,quantity,recipe_snapshot,created_at) VALUES(?,?,?,?,?,?)");for(const [stockId,value] of needed){insert.run(randomUUID(),orderId,stockId,value.quantity,value.snapshot,new Date().toISOString());sqlite.prepare("UPDATE stock_items SET reserved=reserved+?,updated_at=? WHERE id=?").run(value.quantity,new Date().toISOString(),stockId);}}
function consumeOrder(id:string,overrideReason?:string){const rows=sqlite.prepare("SELECT r.stock_item_id,r.quantity,s.on_hand,s.average_cost,s.name FROM stock_reservations r JOIN stock_items s ON s.id=r.stock_item_id WHERE r.order_id=?").all(id) as any[],short=rows.filter(row=>row.on_hand<row.quantity);if(short.length&&!overrideReason)throw new Error(`Insufficient stock: ${short.map(row=>row.name).join(", ")}. Provide an override reason to continue.`);let cost=0;for(const row of rows){sqlite.prepare("UPDATE stock_items SET on_hand=on_hand-?,reserved=MAX(0,reserved-?),updated_at=? WHERE id=?").run(row.quantity,row.quantity,new Date().toISOString(),row.stock_item_id);sqlite.prepare("INSERT INTO stock_ledger(id,stock_item_id,transaction_type,quantity_delta,unit_cost,order_id,reason,override_reason,occurred_at,created_at) VALUES(?,?,'consumption',?,?,?,?,?,?,?)").run(randomUUID(),row.stock_item_id,-row.quantity,row.average_cost,id,"Order preparation",overrideReason??null,new Date().toISOString(),new Date().toISOString());cost+=row.quantity*row.average_cost;}sqlite.prepare("DELETE FROM stock_reservations WHERE order_id=?").run(id);sqlite.prepare("UPDATE orders SET ingredient_cost=? WHERE id=?").run(cost,id);}
export function updateOrderStatus(id:string,status:string,overrideReason?:string){sqlite.transaction(()=>{const current=sqlite.prepare("SELECT status FROM orders WHERE id=?").get(id) as {status:string}|undefined;if(!current)throw new Error("Order not found.");if(status==="preparing"&&current.status!=="preparing")consumeOrder(id,overrideReason);if(status==="cancelled"&&!["preparing","ready","completed"].includes(current.status))releaseOrderReservations(id);if(status==="confirmed"&&current.status!=="confirmed")reserveOrder(id);sqlite.prepare("UPDATE orders SET status=?,updated_at=? WHERE id=?").run(status,new Date().toISOString(),id);})();}
export function addPayment(input:PaymentInput){const kind=input.orderKind??"local",occurredAt=input.occurredAt??input.receivedAt!,direction=input.direction??input.status??"received",target=kind==="local"?"orders":"cloud_orders";const order=sqlite.prepare(`SELECT total FROM ${target} WHERE id=?`).get(input.orderId) as {total:number}|undefined;if(!order)throw new Error("Order not found.");const totals=sqlite.prepare("SELECT COALESCE(SUM(CASE WHEN direction='received' THEN amount ELSE 0 END),0) received,COALESCE(SUM(CASE WHEN direction='refunded' THEN amount ELSE 0 END),0) refunded FROM unified_payments WHERE order_kind=? AND order_id=?").get(kind,input.orderId) as {received:number;refunded:number};const net=Number(totals.received)-Number(totals.refunded);if(direction==="received"&&input.amount>Number(order.total)-net)throw new Error("Receipt cannot exceed the outstanding balance.");if(direction==="refunded"&&input.amount>net)throw new Error("Refund cannot exceed the net amount received.");sqlite.transaction(()=>{sqlite.prepare("INSERT INTO unified_payments(id,order_kind,order_id,amount,occurred_at,method,direction,notes,created_at) VALUES(?,?,?,?,?,?,?,?,?)").run(randomUUID(),kind,input.orderId,input.amount,occurredAt,input.method,direction,input.notes??"",new Date().toISOString());if(kind==="local"){const balance=net+(direction==="received"?input.amount:-input.amount);sqlite.prepare("UPDATE orders SET payment_status=?,updated_at=? WHERE id=?").run(balance<=0?"unpaid":balance>=Number(order.total)?"paid":"partial",new Date().toISOString(),input.orderId);}})();}
export function saveExpense(input: ExpenseInput) { const id=input.id??randomUUID(); sqlite.prepare("INSERT INTO expenses(id,date,category,description,amount,payment_method,notes) VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET date=excluded.date,category=excluded.category,description=excluded.description,amount=excluded.amount,payment_method=excluded.payment_method,notes=excluded.notes").run(id,input.date,input.category,input.description,input.amount,input.paymentMethod,input.notes); return id; }
export function removeExpense(id:string){ sqlite.prepare("DELETE FROM expenses WHERE id=?").run(id); }
export function savePublication(payload:Publication){ const now=new Date().toISOString();sqlite.transaction(()=>{sqlite.prepare("INSERT INTO menu_publications(id,service_date,payload,published_at) VALUES(?,?,?,?)").run(randomUUID(),payload.date,JSON.stringify(payload),now);sqlite.prepare("INSERT INTO current_publication(publication_key,payload,published_at) VALUES('current',?,?) ON CONFLICT(publication_key) DO UPDATE SET payload=excluded.payload,published_at=excluded.published_at").run(JSON.stringify(payload),now);markDirty("publication","current",payload);})(); }
export function publicationHistory(){ return sqlite.prepare("SELECT id,service_date,payload,published_at FROM menu_publications ORDER BY published_at DESC LIMIT 50").all(); }
export function getCurrentPublication(){const row=sqlite.prepare("SELECT payload FROM current_publication WHERE publication_key='current'").get() as {payload:string}|undefined;return row?publicationSchema.parse(JSON.parse(row.payload)):null;}

function markDirty(entityType:string,entityId:string,payload:unknown){sqlite.prepare("INSERT INTO sync_state(entity_type,entity_id,dirty,base_payload) VALUES(?,?,1,NULL) ON CONFLICT(entity_type,entity_id) DO UPDATE SET dirty=1").run(entityType,entityId);}
export function validateCatalogItemReferences(item:CatalogItem){const category=sqlite.prepare("SELECT active FROM menu_categories WHERE id=?").get(item.categoryId) as {active:number}|undefined;if(!category)throw new Error("Select an existing catalog category.");for(const group of item.bundleGroups){for(const choice of group.choices){const dish=sqlite.prepare("SELECT item_type,available,archived_at FROM menu_items WHERE id=?").get(choice.itemId) as {item_type:string;available:number;archived_at:string|null}|undefined;if(!dish||dish.item_type!=="dish"||!dish.available||dish.archived_at)throw new Error(`Bundle choice ${choice.itemId} must reference an available, active dish.`);}}}
export function saveCatalogItem(item:CatalogItem){const now=new Date().toISOString();sqlite.transaction(()=>{sqlite.prepare("INSERT INTO menu_items(id,category_id,item_type,name,description,portion,price,image,available,is_new,tags,display_order,archived_at,web_compatible,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET category_id=excluded.category_id,item_type=excluded.item_type,name=excluded.name,description=excluded.description,portion=excluded.portion,price=excluded.price,image=excluded.image,available=excluded.available,is_new=excluded.is_new,tags=excluded.tags,display_order=excluded.display_order,archived_at=excluded.archived_at,updated_at=excluded.updated_at").run(item.id,item.categoryId,item.type,item.name,item.description,item.portion,item.price,item.image??"food-placeholder.jpeg",item.available?1:0,item.isNew?1:0,JSON.stringify(item.tags),item.order,item.archived?now:null,1,now);sqlite.prepare("DELETE FROM bundle_option_groups WHERE item_id=?").run(item.id);const groupInsert=sqlite.prepare("INSERT INTO bundle_option_groups(id,item_id,name,min_choices,max_choices,display_order) VALUES(?,?,?,?,?,?)"),choiceInsert=sqlite.prepare("INSERT INTO bundle_option_choices(id,group_id,item_id,upgrade_price,available,display_order) VALUES(?,?,?,?,?,?)");for(const group of item.bundleGroups){groupInsert.run(group.id,item.id,group.name,group.minChoices,group.maxChoices,group.order);for(const choice of group.choices)choiceInsert.run(choice.id,group.id,choice.itemId,choice.upgradePrice,choice.available?1:0,choice.order);}markDirty("catalog_item",item.id,item);})();}
export function saveCatalogItemCompatibility(id:string,webCompatible:boolean){sqlite.prepare("UPDATE menu_items SET web_compatible=? WHERE id=?").run(webCompatible?1:0,id);}
export function archiveCatalogItem(id:string,archived:boolean){const now=new Date().toISOString();sqlite.prepare("UPDATE menu_items SET archived_at=?,updated_at=? WHERE id=?").run(archived?now:null,now,id);markDirty("catalog_item",id,{archived});}
export function saveCatalogCategory(category:CatalogCategory){const now=new Date().toISOString();sqlite.prepare("INSERT INTO menu_categories(id,name,sort_order,active,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,sort_order=excluded.sort_order,active=excluded.active,updated_at=excluded.updated_at").run(category.id,category.name,category.order,category.active?1:0,now);markDirty("catalog_category",category.id,category);}
export function setCatalogCategoryActive(id:string,active:boolean){const current=sqlite.prepare("SELECT id,name,sort_order AS 'order',active FROM menu_categories WHERE id=?").get(id) as any;if(!current)throw new Error("Catalog category not found.");saveCatalogCategory({...current,active});}
export function validatePublicationCatalog(payload:Publication){const catalog=getCatalog(),categories=catalog.categories as CatalogCategory[],selected=payload.itemIds.map((id)=>catalog.items.find((item)=>item.id===id));if(selected.some((item)=>!item))throw new Error("The menu contains an item that no longer exists.");const invalid=selected.find((item)=>item&&!isPublishableItem(item,categories));if(invalid)throw new Error(`${invalid.name} is unavailable, archived, incompatible, or belongs to an inactive category.`);}
function runtimeConfigFromRows(rows:{settings_key:string;payload:string}[]):RuntimeConfig{const map=Object.fromEntries(rows.map((row)=>{let payload:unknown;try{payload=JSON.parse(row.payload);}catch{payload=undefined;}return[row.settings_key,payload];}));return runtimeConfigFromSettings(map);}
function repairRuntimeSettings(){const rows=sqlite.prepare("SELECT settings_key,payload FROM app_settings").all() as {settings_key:string;payload:string}[],config=runtimeConfigFromRows(rows),upsert=sqlite.prepare("INSERT INTO app_settings(settings_key,payload,updated_at) VALUES(?,?,COALESCE((SELECT updated_at FROM app_settings WHERE settings_key=?),?)) ON CONFLICT(settings_key) DO UPDATE SET payload=excluded.payload");for(const [key,payload] of [["site",config.site],["operations",config.operations],["notification",config.notifications],["announcement",config.announcements],["service_area",config.serviceArea],["ordering_platforms",config.orderingPlatforms],["public_location",config.publicLocation]] as const)upsert.run(key,JSON.stringify(payload),key,new Date().toISOString());}
export function getRuntimeConfig():RuntimeConfig{const rows=sqlite.prepare("SELECT settings_key,payload FROM app_settings").all() as {settings_key:string;payload:string}[];return runtimeConfigFromRows(rows);}
export function saveRuntimeConfig(config:RuntimeConfig){const value=runtimeConfigSchema.parse(config),now=new Date().toISOString(),upsert=sqlite.prepare("INSERT INTO app_settings(settings_key,payload,updated_at) VALUES(?,?,?) ON CONFLICT(settings_key) DO UPDATE SET payload=excluded.payload,updated_at=excluded.updated_at");sqlite.transaction(()=>{for(const [key,payload] of [["site",value.site],["operations",value.operations],["notification",value.notifications],["announcement",value.announcements],["service_area",value.serviceArea],["ordering_platforms",value.orderingPlatforms],["public_location",value.publicLocation]] as const){upsert.run(key,JSON.stringify(payload),now);markDirty("app_setting",key,payload);}})();}
export function listCloudOrders(query=""){const term=`%${query}%`;return sqlite.prepare("SELECT id,order_number,service_date,fulfilment,total,status,created_at,updated_at,json_extract(customer_snapshot,'$.name') customer_name,json_extract(customer_snapshot,'$.phone') phone FROM cloud_orders WHERE ?='' OR order_number LIKE ? OR customer_snapshot LIKE ? ORDER BY created_at DESC LIMIT 500").all(query,term,term);}
export function listCloudOrdersForRange(range:DateRange){return sqlite.prepare("SELECT id,order_number,service_date,fulfilment,total,status,created_at,updated_at,json_extract(customer_snapshot,'$.name') customer_name,json_extract(customer_snapshot,'$.phone') phone FROM cloud_orders WHERE service_date BETWEEN ? AND ? ORDER BY created_at DESC").all(range.from,range.to);}
export function listCloudOrdersCreatedInRange(range:DateRange){return sqlite.prepare("SELECT id,order_number,service_date,fulfilment,total,status,created_at,updated_at,json_extract(customer_snapshot,'$.name') customer_name,json_extract(customer_snapshot,'$.phone') phone FROM cloud_orders WHERE date(created_at,'+5 hours','+30 minutes') BETWEEN ? AND ? ORDER BY created_at DESC LIMIT 500").all(range.from,range.to);}
export function cloudOrderDetail(id:string){const order=sqlite.prepare("SELECT * FROM cloud_orders WHERE id=?").get(id) as any;if(!order)return null;const customer=JSON.parse(order.customer_snapshot),address=JSON.parse(order.address_snapshot);return{...order,customer_snapshot:customer,address_snapshot:address,customer_name:customer.name??"",customer_phone:customer.phone??"",address:address.formattedAddress??address.address??"",lines:(sqlite.prepare("SELECT * FROM cloud_order_lines WHERE order_id=? ORDER BY id").all(id) as any[]).map(normalizeCloudOrderLine),events:(sqlite.prepare("SELECT * FROM cloud_order_events WHERE order_id=? ORDER BY created_at").all(id) as any[]).map((event)=>({...event,payload:JSON.parse(event.payload)}))};}
export function updateCloudOrderStatus(id:string,status:string){sqlite.prepare("UPDATE cloud_orders SET status=?,updated_at=? WHERE id=?").run(status,new Date().toISOString(),id);markDirty("cloud_order_status",id,{status});}

export function orderingSources():OrderingSource[]{const configured=getRuntimeConfig().orderingPlatforms.filter((entry)=>entry.status==="available").sort((a,b)=>a.order-b.order).map(({id,name})=>({id,name}));return[{id:"direct",name:"Direct order"},...configured.filter((entry)=>entry.id!=="direct")];}
export function validOrderingSource(source:OrderingSource,orderId?:string){if(orderingSources().some((entry)=>entry.id===source.id&&entry.name===source.name))return true;if(!orderId)return false;const existing=sqlite.prepare("SELECT source_platform_id id,source_platform_name name FROM orders WHERE id=?").get(orderId) as OrderingSource|undefined;return existing?.id===source.id&&existing?.name===source.name;}
function paymentColumns(kind:"local"|"online"){return`COALESCE((SELECT SUM(CASE WHEN direction='received' THEN amount ELSE 0 END) FROM unified_payments WHERE order_kind='${kind}' AND order_id=o.id),0) paid,COALESCE((SELECT SUM(CASE WHEN direction='refunded' THEN amount ELSE 0 END) FROM unified_payments WHERE order_kind='${kind}' AND order_id=o.id),0) refunded`;}
function manualOrderRows(range:DateRange){return sqlite.prepare(`SELECT o.*,c.name customer_name,c.phone,c.email,${paymentColumns("local")},(SELECT GROUP_CONCAT(name||' x'||quantity,'; ') FROM order_lines WHERE order_id=o.id) items FROM orders o JOIN customers c ON c.id=o.customer_id WHERE o.service_date BETWEEN ? AND ? ORDER BY o.created_at DESC`).all(range.from,range.to) as any[];}
function onlineOrderRows(range:DateRange){return sqlite.prepare(`SELECT o.*,json_extract(customer_snapshot,'$.name') customer_name,json_extract(customer_snapshot,'$.phone') phone,json_extract(customer_snapshot,'$.email') email,${paymentColumns("online")},(SELECT GROUP_CONCAT(json_extract(item_snapshot,'$.name')||' x'||quantity,'; ') FROM cloud_order_lines WHERE order_id=o.id) items FROM cloud_orders o WHERE o.service_date BETWEEN ? AND ? ORDER BY o.created_at DESC`).all(range.from,range.to) as any[];}
function manualSummary(row:any):UnifiedOrderSummary{const net=Number(row.paid)-Number(row.refunded);return{kind:"manual",id:row.id,reference:row.order_number,customerName:row.customer_name,phone:row.phone,email:row.email??null,serviceType:row.service_type??"general",serviceDate:row.service_date,serviceEndDate:row.service_end_date??null,serviceStartTime:row.service_start_time??null,serviceEndTime:row.service_end_time??null,fulfilment:row.fulfilment,sourceId:row.source_platform_id??row.source,sourceName:row.source_platform_name??row.source,status:row.status,paymentStatus:net<=0?"unpaid":net>=row.total?"paid":"partial",total:Number(row.total),paid:Number(row.paid),refunded:Number(row.refunded),outstanding:Math.max(0,Number(row.total)-net),ingredientCost:Number(row.ingredient_cost??0),notes:row.notes??"",createdAt:row.created_at,items:row.items??""};}
function onlineSummary(row:any):UnifiedOrderSummary{const net=Number(row.paid)-Number(row.refunded);return{kind:"online",id:row.id,reference:row.order_number,customerName:row.customer_name??"",phone:row.phone??"",email:row.email??null,serviceType:"preorder",serviceDate:row.service_date,serviceEndDate:null,serviceStartTime:null,serviceEndTime:null,fulfilment:row.fulfilment,sourceId:"website",sourceName:"Website",status:row.status,paymentStatus:net<=0?"unpaid":net>=row.total?"paid":"partial",total:Number(row.total),paid:Number(row.paid),refunded:Number(row.refunded),outstanding:Math.max(0,Number(row.total)-net),ingredientCost:0,notes:row.notes??"",createdAt:row.created_at,items:row.items??""};}
export function listUnifiedOrders(query:UnifiedOrderQuery):UnifiedOrderSummary[]{const rows=[...(query.kind!=="manual"?onlineOrderRows(query.range).map(onlineSummary):[]),...(query.kind!=="online"?manualOrderRows(query.range).map(manualSummary):[])];const term=query.search.toLowerCase();return rows.filter((row)=>!query.source||row.sourceId===query.source).filter((row)=>!term||`${row.reference} ${row.customerName} ${row.phone} ${row.email??""} ${row.sourceName} ${row.items}`.toLowerCase().includes(term)).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));}
export function unifiedOrderDetail(kind:"online"|"manual",id:string):UnifiedOrderDetail|null{const paymentKind=kind==="online"?"online":"local",payments=sqlite.prepare("SELECT * FROM unified_payments WHERE order_kind=? AND order_id=? ORDER BY occurred_at").all(paymentKind,id) as any[],totals=payments.reduce((value,row)=>{value[row.direction]+=Number(row.amount);return value},{received:0,refunded:0});if(kind==="online"){const detail=cloudOrderDetail(id);if(!detail)return null;const row=onlineSummary({...detail,paid:totals.received,refunded:totals.refunded,customer_name:detail.customer_name,phone:detail.customer_phone,email:detail.customer_snapshot?.email,items:detail.lines.map((line:any)=>`${line.name} x${line.quantity}`).join("; ")});return{...row,address:detail.address,adjustmentLabel:"",adjustmentAmount:0,serviceDetails:{occasion:"",guestCount:null,dietary:"",packaging:""},enquiryId:null,enquiryReference:null,tiffinPlanId:null,payments,lines:detail.lines.map((line:any)=>({id:line.id,menuItemId:line.item_id,name:line.name,quantity:line.quantity,unitPrice:line.unit_price,lineTotal:line.line_total}))};}const row=sqlite.prepare(`SELECT o.*,c.name customer_name,c.phone,c.email,${paymentColumns("local")},(SELECT GROUP_CONCAT(name||' x'||quantity,'; ') FROM order_lines WHERE order_id=o.id) items FROM orders o JOIN customers c ON c.id=o.customer_id WHERE o.id=?`).get(id) as any;if(!row)return null;return{...manualSummary(row),address:row.address??"",adjustmentLabel:row.adjustment_label,adjustmentAmount:Number(row.adjustment_amount),serviceDetails:row.service_details?JSON.parse(row.service_details):{occasion:"",guestCount:null,dietary:"",packaging:""},enquiryId:row.enquiry_id,enquiryReference:row.enquiry_reference,tiffinPlanId:row.tiffin_plan_id,payments,lines:(sqlite.prepare("SELECT id,menu_item_id menuItemId,name,quantity,unit_price unitPrice,line_total lineTotal,recipe_snapshot recipeSnapshot FROM order_lines WHERE order_id=? ORDER BY rowid").all(id) as any[]).map(line=>({...line,recipeSnapshot:line.recipeSnapshot?JSON.parse(line.recipeSnapshot):null}))};}

export function dashboard(range:DateRange){
  const cash=sqlite.prepare("SELECT COALESCE(SUM(CASE WHEN direction='received' THEN amount ELSE 0 END),0) receipts,COALESCE(SUM(CASE WHEN direction='refunded' THEN amount ELSE 0 END),0) refunds FROM unified_payments WHERE date(occurred_at) BETWEEN ? AND ?").get(range.from,range.to) as any;
  const revenue=Number(cash.receipts)-Number(cash.refunds);
  const expenses=(sqlite.prepare("SELECT COALESCE(SUM(amount),0) value FROM expenses WHERE date BETWEEN ? AND ?").get(range.from,range.to) as any).value;
  const combined=listUnifiedOrders({kind:"all",range,search:"",source:""}),active=combined.filter((row)=>row.status!=="cancelled"),outstanding=active.reduce((sum,row)=>sum+row.outstanding,0);
  const billedValue=active.reduce((sum,row)=>sum+row.total,0),ingredientCost=active.reduce((sum,row)=>sum+row.ingredientCost,0),groups=new Map<string,any>();
  for(const row of active){const key=`${row.serviceType}|${row.sourceName}`,entry=groups.get(key)??{serviceType:row.serviceType,origin:row.sourceName,billedValue:0,received:0,refunded:0,outstanding:0,ingredientCost:0};entry.billedValue+=row.total;entry.received+=row.paid;entry.refunded+=row.refunded;entry.outstanding+=row.outstanding;entry.ingredientCost+=row.ingredientCost;groups.set(key,entry);}
  return {billedValue,receipts:Number(cash.receipts),refunds:Number(cash.refunds),revenue,expenses,profit:revenue-expenses,orderCount:combined.length,outstanding,ingredientCost,operationalMargin:billedValue-ingredientCost,averageOrder:active.length?billedValue/active.length:0,breakdown:[...groups.values()],recentOrders:combined.slice(0,6).map((row)=>({customer_name:row.customerName,created_at:row.createdAt,service_date:row.serviceDate,status:row.status,total:row.total})),expenseByCategory:sqlite.prepare("SELECT category,SUM(amount) total FROM expenses WHERE date BETWEEN ? AND ? GROUP BY category ORDER BY total DESC").all(range.from,range.to) };
}
export function getSettings(){ return Object.fromEntries((sqlite.prepare("SELECT key,value FROM settings").all() as {key:string;value:string}[]).map(row=>[row.key,row.value])); }
export function setSettings(values:Record<string,string>){ const upsert=sqlite.prepare("INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value"); sqlite.transaction(()=>Object.entries(values).forEach(([key,value])=>upsert.run(key,value)))(); }
export function listInbox(){ return sqlite.prepare("SELECT * FROM whatsapp_imports ORDER BY received_at DESC").all(); }
export function addInbox(item:{id:string;sender:string;message:string;receivedAt:string;parsedPayload:string|null}){ sqlite.prepare("INSERT OR IGNORE INTO whatsapp_imports(id,meta_message_id,sender,message,parsed_payload,status,received_at) VALUES(?,?,?,?,?,'new',?)").run(item.id,item.id,item.sender,item.message,item.parsedPayload,item.receivedAt); }
export function finishInbox(id:string,orderId:string|null){sqlite.prepare("UPDATE whatsapp_imports SET status=?,order_id=? WHERE meta_message_id=?").run(orderId?"imported":"unmatched",orderId,id);}
export function closeDatabase(){ sqlite?.close(); }
export function rawDatabase(){ return sqlite; }
