import { neon } from "@neondatabase/serverless";
import { rawDatabase } from "./database";
import { databaseConnection } from "./services";
import { loadEnquiryCountSafely } from "../shared/enquiry-connectivity";

export type EnquiryDetail={id:string;reference:string;type:"party"|"bulk"|"tiffin";status:"new"|"contacted"|"quoted"|"converted"|"closed";seenAt:string|null;customer:{name:string;phone:string;email?:string|null};address:Record<string,unknown>|null;requirements:Record<string,unknown>;items:Array<{id:string;name:string;portion:string;price:number}>;source:string;createdAt:string;updatedAt:string;events?:Array<Record<string,unknown>>};
const rowToDetail=(row:Record<string,unknown>):EnquiryDetail=>({id:String(row.id),reference:String(row.reference),type:String(row.enquiry_type) as EnquiryDetail["type"],status:String(row.status??"new") as EnquiryDetail["status"],seenAt:row.seen_at?String(row.seen_at):null,customer:row.customer_snapshot as EnquiryDetail["customer"],address:(row.address_snapshot??null) as Record<string,unknown>|null,requirements:row.requirements as Record<string,unknown>,items:(row.item_snapshots??[]) as EnquiryDetail["items"],source:String(row.source_ui),createdAt:String(row.created_at),updatedAt:String(row.updated_at??row.created_at)});
export function notificationPreference(){return Boolean((rawDatabase().prepare("SELECT enabled FROM enquiry_notification_state WHERE singleton=1").get() as {enabled:number}).enabled)}
export function setNotificationPreference(enabled:boolean){rawDatabase().prepare("UPDATE enquiry_notification_state SET enabled=? WHERE singleton=1").run(enabled?1:0)}
export async function pollEnquiries(){const db=rawDatabase(),state=db.prepare("SELECT cursor_created_at,cursor_id,enabled FROM enquiry_notification_state WHERE singleton=1").get() as {cursor_created_at:string|null;cursor_id:string|null;enabled:number};const connection=databaseConnection();if(!connection.url)throw new Error("Neon is not configured.");const sql=neon(connection.url);if(!state.cursor_created_at){const newest=await sql`SELECT id,created_at FROM enquiries ORDER BY created_at DESC,id DESC LIMIT 1`;if(newest[0])db.prepare("UPDATE enquiry_notification_state SET cursor_created_at=?,cursor_id=? WHERE singleton=1").run(String(newest[0].created_at),String(newest[0].id));return{items:[] as EnquiryDetail[],enabled:Boolean(state.enabled)};}const rows=await sql`SELECT id,reference,enquiry_type,status,seen_at,customer_snapshot,requirements,item_snapshots,source_ui,created_at,updated_at FROM enquiries WHERE (created_at,id)>(${state.cursor_created_at},${state.cursor_id}) ORDER BY created_at,id LIMIT 100`;const items=rows.map(rowToDetail);if(items.length){const last=items.at(-1)!;db.prepare("UPDATE enquiry_notification_state SET cursor_created_at=?,cursor_id=? WHERE singleton=1").run(last.createdAt,last.id);}return{items,enabled:Boolean(state.enabled)}}
export async function listEnquiries(input:{query:string;type:string;status:string;from:string;to:string}){const sql=neon(databaseConnection().url!);const rows=await sql`SELECT id,reference,enquiry_type,status,seen_at,customer_snapshot,address_snapshot,requirements,item_snapshots,source_ui,created_at,updated_at FROM enquiries WHERE (${input.query}='' OR reference ILIKE ${`%${input.query}%`} OR customer_snapshot::text ILIKE ${`%${input.query}%`} OR requirements::text ILIKE ${`%${input.query}%`}) AND (${input.type}='all' OR enquiry_type=${input.type}) AND (${input.status}='all' OR status=${input.status}) AND created_at::date BETWEEN ${input.from}::date AND ${input.to}::date ORDER BY created_at DESC LIMIT 500`;return rows.map(rowToDetail)}
export async function enquiryDetail(id:string){const connection=databaseConnection();if(!connection.url)throw new Error("Neon is not configured.");const sql=neon(connection.url);const rows=await sql`SELECT id,reference,enquiry_type,status,seen_at,customer_snapshot,address_snapshot,requirements,item_snapshots,source_ui,created_at,updated_at FROM enquiries WHERE id=${id}`;if(!rows[0])return null;const detail=rowToDetail(rows[0]);detail.events=await sql`SELECT event_type,payload,created_at FROM enquiry_events WHERE enquiry_id=${id} ORDER BY created_at`;return detail}
export async function markEnquirySeen(id:string){const sql=neon(databaseConnection().url!);await sql`SELECT gruhswad_mark_enquiry_seen(${id}::uuid)`;return enquiryDetail(id)}
export async function updateEnquiryStatus(id:string,status:EnquiryDetail["status"]){const sql=neon(databaseConnection().url!);await sql`SELECT gruhswad_transition_enquiry(${id}::uuid,${status})`;return enquiryDetail(id)}
export async function newEnquiryCount(){return loadEnquiryCountSafely(async()=>{const connection=databaseConnection();if(!connection.url)throw new Error("Neon is not configured.");const sql=neon(connection.url);const rows=await sql`SELECT COUNT(*) count FROM enquiries WHERE seen_at IS NULL`;return Number(rows[0].count)})}
