import { join } from "node:path";
import { existsSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { app, BrowserWindow, ipcMain } from "electron";
import updater from "electron-updater";
import { catalogCategorySchema, catalogItemSchema, cloudOrderStatusSchema, expenseInputSchema, orderInputSchema, orderStatusSchema, paymentInputSchema, publicationSchema, runtimeConfigSchema, type DateRange } from "../shared/contracts";
import { addPayment, archiveCatalogItem, cloudOrderDetail, dashboard, getCatalog, getCurrentPublication, getRuntimeConfig, getSettings, initializeDatabase, listCloudOrders, listExpenses, listInbox, listOrders, publicationHistory, removeExpense, saveCatalogCategory, saveCatalogItem, saveCatalogItemCompatibility, saveExpense, saveOrder, saveRuntimeConfig, setCatalogCategoryActive, setSettings, updateCloudOrderStatus, updateOrderStatus, validateCatalogItemReferences } from "./database";
import { backupDatabase, databaseConnection, exportCsv, loadSecrets, loadStoredSecrets, publishToGruhswad, restoreDatabase, saveSecrets, syncInbox } from "./services";
import { listConflicts, previewPull, previewPush, pullFromNeon, pushToNeon, resolveConflict, syncHistory, syncStatus } from "./sync-engine";
import { exportMenuPdf } from "./menu-pdf";
import { exportOneDayMenuPdf } from "./one-day-menu-pdf";
import { exportPhotoOneDayMenuPdf } from "./one-day-menu-photo-pdf";

let window:BrowserWindow|null=null;
const { autoUpdater } = updater;
if(process.env.GRUHSWAD_TEST_USER_DATA)app.setPath("userData",process.env.GRUHSWAD_TEST_USER_DATA);
function registerIpc(){
  ipcMain.handle("dashboard",(_e,range:DateRange)=>dashboard(range));
  ipcMain.handle("orders:list",(_e,range?:DateRange)=>listOrders(range)); ipcMain.handle("orders:save",(_e,input)=>saveOrder(orderInputSchema.parse(input))); ipcMain.handle("orders:status",(_e,id,status)=>updateOrderStatus(id,orderStatusSchema.parse(status))); ipcMain.handle("orders:payment",(_e,input)=>addPayment(paymentInputSchema.parse(input)));
  ipcMain.handle("expenses:list",(_e,range?:DateRange)=>listExpenses(range)); ipcMain.handle("expenses:save",(_e,input)=>saveExpense(expenseInputSchema.parse(input))); ipcMain.handle("expenses:remove",(_e,id)=>removeExpense(id));
  ipcMain.handle("catalog:get",()=>getCatalog());ipcMain.handle("catalog:save",(_e,input)=>{const item=catalogItemSchema.parse(input);validateCatalogItemReferences(item);saveCatalogItem(item);saveCatalogItemCompatibility(item.id,item.webCompatible);});ipcMain.handle("catalog:archive",(_e,id,archived)=>archiveCatalogItem(String(id),Boolean(archived)));ipcMain.handle("catalog:export-pdf",()=>exportMenuPdf());
  ipcMain.handle("catalog:category-save",(_e,input)=>saveCatalogCategory(catalogCategorySchema.parse(input)));ipcMain.handle("catalog:category-active",(_e,id,active)=>setCatalogCategoryActive(String(id),Boolean(active)));
  ipcMain.handle("operations:get",()=>getRuntimeConfig());ipcMain.handle("operations:save",(_e,input)=>saveRuntimeConfig(runtimeConfigSchema.parse(input)));
  ipcMain.handle("menu:catalog",()=>getCatalog()); ipcMain.handle("menu:history",()=>publicationHistory());ipcMain.handle("menu:current",()=>getCurrentPublication()); ipcMain.handle("menu:publish",(_e,input)=>publishToGruhswad(publicationSchema.parse(input)));ipcMain.handle("menu:export-pdf",()=>exportOneDayMenuPdf());ipcMain.handle("menu:export-photo-pdf",()=>exportPhotoOneDayMenuPdf());
  ipcMain.handle("cloud-orders:list",(_e,query)=>listCloudOrders(String(query??"")));ipcMain.handle("cloud-orders:detail",(_e,id)=>cloudOrderDetail(String(id)));ipcMain.handle("cloud-orders:status",(_e,id,status)=>updateCloudOrderStatus(String(id),cloudOrderStatusSchema.parse(status)));
  ipcMain.handle("sync:status",()=>syncStatus());ipcMain.handle("sync:preview-pull",()=>previewPull());ipcMain.handle("sync:pull",()=>pullFromNeon());ipcMain.handle("sync:preview-push",()=>previewPush());ipcMain.handle("sync:push",()=>pushToNeon());ipcMain.handle("sync:conflicts",()=>listConflicts());ipcMain.handle("sync:resolve",(_e,id,resolution)=>resolveConflict(String(id),resolution));ipcMain.handle("sync:history",()=>syncHistory());
  ipcMain.handle("inbox:list",()=>listInbox()); ipcMain.handle("inbox:sync",()=>syncInbox());
  ipcMain.handle("settings:get",()=>({...getSettings(),hasNeonUrl:Boolean(loadSecrets().neonDatabaseUrl),hasInboxToken:Boolean(loadSecrets().inboxToken)})); ipcMain.handle("settings:set",(_e,values,secrets)=>{setSettings(values);if(secrets){const next={...loadStoredSecrets()};for(const [key,value] of Object.entries(secrets) as [keyof typeof next,string][])if(value?.trim())next[key]=value.trim();saveSecrets(next);}}); ipcMain.handle("settings:backup",()=>backupDatabase()); ipcMain.handle("settings:restore",()=>restoreDatabase());
  ipcMain.handle("reports:export",(_e,kind,range)=>exportCsv(kind,range)); ipcMain.handle("updates:check",()=>autoUpdater.checkForUpdates()); ipcMain.handle("updates:install",()=>autoUpdater.quitAndInstall());
}
async function startStartupPull(){let configured=true;try{configured=databaseConnection().configured;}catch{}if(!configured){window?.webContents.send("sync:startup-pull-settled");return;}try{await pullFromNeon();window?.webContents.send("sync:startup-pull-complete");}catch{/* Startup remains silent; the failed run is visible in Sync Centre. */}finally{window?.webContents.send("sync:startup-pull-settled");}}
function createWindow(){window=new BrowserWindow({width:1440,height:920,minWidth:1080,minHeight:700,backgroundColor:"#fff8f1",webPreferences:{preload:join(__dirname,"../preload/index.cjs"),nodeIntegration:false,contextIsolation:true,sandbox:true}});window.webContents.once("did-finish-load",()=>{void startStartupPull();});const devUrl=process.env.ELECTRON_RENDERER_URL;if(!app.isPackaged&&devUrl)window.loadURL(devUrl);else window.loadFile(join(__dirname,"../renderer/index.html"));}
app.whenReady().then(async()=>{const databasePath=join(app.getPath("userData"),"gruhswad-admin.db"),pendingPath=join(app.getPath("userData"),"restore-pending.db");if(existsSync(pendingPath)){rmSync(databasePath,{force:true});renameSync(pendingPath,databasePath);}initializeDatabase(databasePath,app.isPackaged?join(process.resourcesPath,"drizzle"):join(process.cwd(),"drizzle"));if(process.env.GRUHSWAD_SYNC_SMOKE==="1"){try{const result=await pullFromNeon();writeFileSync(join(app.getPath("userData"),"sync-smoke.json"),JSON.stringify({ok:true,result}));}catch(error){writeFileSync(join(app.getPath("userData"),"sync-smoke.json"),JSON.stringify({ok:false,error:String(error)}));process.exitCode=1;}finally{app.quit();}return;}registerIpc();createWindow(); if(app.isPackaged)autoUpdater.checkForUpdatesAndNotify();});
for(const event of ["checking-for-update","update-available","update-not-available","download-progress","update-downloaded","error"] as const) autoUpdater.on(event,(value:any)=>window?.webContents.send("updates:status",event==="download-progress"?`Downloading ${Math.round(value.percent)}%`:event));
app.on("window-all-closed",()=>{if(process.platform!=="darwin")app.quit();}); app.on("activate",()=>{if(BrowserWindow.getAllWindows().length===0)createWindow();});
