import { join } from "node:path";
import { existsSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { app, BrowserWindow, clipboard, dialog, ipcMain, Notification, protocol, shell } from "electron";
import updater from "electron-updater";
import { catalogCategorySchema, catalogItemSchema, cloudOrderStatusSchema, customerInputSchema, expenseInputSchema, orderInputSchema, orderStatusSchema, paymentInputSchema, publicationSchema, purchaseInputSchema,receiptExpenseInputSchema,recipeInputSchema,runtimeConfigSchema,stockAdjustmentSchema,stockItemInputSchema,tiffinPlanInputSchema,unifiedOrderQuerySchema, type DateRange, type NotificationResult } from "../shared/contracts";
import { addPayment, archiveCatalogItem, archiveCustomer, cloudOrderDetail, customerContact, dashboard, getCatalog, getCurrentPublication, getRuntimeConfig, getSettings, initializeDatabase, listCloudOrders, listCustomers, listExpenses, listInbox, listOrders, listUnifiedOrders, orderingSources, publicationHistory, rawDatabase, removeExpense, saveCatalogCategory, saveCatalogItem, saveCatalogItemCompatibility, saveCustomer, saveExpense, saveOrder, saveRuntimeConfig, setCatalogCategoryActive, setSettings, unifiedOrderDetail, updateCloudOrderStatus, updateOrderStatus, validOrderingSource, validateCatalogItemReferences } from "./database";
import { backupDatabase, databaseConnection, databaseConnectionInfo, exportCsv, importGcsCredentials, loadSecrets, loadStoredSecrets,portableEnvironment, publishToGruhswad, restoreDatabase, saveSecrets, syncInbox } from "./services";
import { listConflicts, previewPull, previewPush, pullFromNeon, pushToNeon, resolveConflict, syncAttention, syncHistory, syncStatus } from "./sync-engine";
import { exitWarningCopy } from "../shared/sync-attention";
import { exportMenuPdf } from "./menu-pdf";
import { exportOneDayMenuPdf } from "./one-day-menu-pdf";
import { exportPhotoOneDayMenuPdf } from "./one-day-menu-photo-pdf";
import { exportMasterMenuImages, exportOneDayMenuImages, previewMasterMenuImages, previewOneDayMenuImages } from "./template-menu-images";
import { cleanupLatestImagePreview, latestImageDataUrl, openLatestImage, showLatestImageInFolder } from "./image-renderer";
import { shareOneDayMenuOnWhatsApp } from "./whatsapp-menu";
import { menuImagePublicationStatus, publishMenuImages } from "./menu-publishing";
import { z } from "zod";
import { catalogImageResponse, chooseCatalogImage, packagedCatalogAssets, saveCatalogItemWithImage } from "./catalog-images";
import { enquiryDetail, listEnquiries, markEnquiryConverted,markEnquirySeen, newEnquiryCount, notificationPreference, pollEnquiries, setNotificationPreference, updateEnquiryStatus } from "./enquiry-notifications";
import { cloneDatabase, profileState, readSelectedProfile, writeSelectedProfile, type LocalDataProfile } from "./local-data-profiles";
import { enquiryNotificationContent } from "../shared/enquiry-arrival";
import {adjustStock,generateTiffinCycle,linkCatalogRecipe,listRecipes,listStock,listTiffinPlans,receiveStock,saveRecipe,saveStockItem,saveTiffinPlan,stockAlerts,stockLedger} from "./operational-data";
import {youtubeEmbedUrl,youtubeDisplayUrl,YOUTUBE_ID} from "../shared/service-operations";
import {applyPendingPortableRestoreSafely,archiveUnreadableProfileCredentials,discardPendingPortableRestore,exportPortableBackup,inspectAndStagePortableBackup as stagePortableBackup,portableBackupSummary} from "./portable-backup";
import {chooseAndReadReceipt,openReceipt,receiptForExpense,saveReceiptExpense} from "./receipt-ocr";
import {runProfileSecretHelper} from "./profile-secret-helper";

let window:BrowserWindow|null=null;
protocol.registerSchemesAsPrivileged([{scheme:"catalog-image",privileges:{standard:true,secure:true,supportFetchAPI:true}}]);
let exitDialogOpen=false;
let allowCloseOnce=false;
let enquiryTimer:ReturnType<typeof setInterval>|null=null,enquiryPolling=false;
const activeNotifications=new Set<Notification>();
let profileOperation=false;
const { autoUpdater } = updater;
const helperArgument=process.argv.indexOf("--gruhswad-profile-secret-helper"),helperRequest=helperArgument>=0?process.argv.slice(helperArgument+1,helperArgument+4):null;if(helperRequest?.[1])app.setPath("userData",helperRequest[1]);const appDataPath=process.env.GRUHSWAD_TEST_APP_DATA||app.getPath("appData");if(!helperRequest&&!process.env.GRUHSWAD_TEST_USER_DATA)applyPendingPortableRestoreSafely(appDataPath);const initialProfileState=profileState(appDataPath,"production"),activeProfile:LocalDataProfile=process.env.GRUHSWAD_TEST_USER_DATA?"production":readSelectedProfile(initialProfileState.selectionPath);
if(!helperRequest&&activeProfile==="intensive-testing")process.env.APP_ENV="prod";
if(!helperRequest){if(process.env.GRUHSWAD_TEST_USER_DATA)app.setPath("userData",process.env.GRUHSWAD_TEST_USER_DATA);else if(process.env.GRUHSWAD_TEST_APP_DATA||activeProfile==="intensive-testing")app.setPath("userData",profileState(appDataPath,activeProfile).profiles.find(profile=>profile.id===activeProfile)!.userDataPath)}
function localProfiles(){return profileState(appDataPath,activeProfile)}
async function inspectAndStagePortableBackup(path:string,password:string){const value=await stagePortableBackup(path,password);if(!value)return null;const profiles=value.profiles.filter(profile=>profile.database).map(profile=>`${profile.id}: SQLite, ${profile.secrets?"credentials":"no credentials"}, ${profile.attachments} attachments`).join("\n"),choice=await dialog.showMessageBox({type:"warning",title:"Apply complete portable restore?",message:`Backup from ${new Date(value.createdAt).toLocaleString()} (app ${value.appVersion})`,detail:`${profiles}\n\nActive profile after restore: ${value.activeProfile}. Existing profiles will be preserved as timestamped safety copies. Neon will not sync automatically.`,buttons:["Cancel","Replace both profiles & relaunch"],defaultId:0,cancelId:0,noLink:true});if(choice.response!==1){discardPendingPortableRestore(path);return null}return value}
function stopBackgroundWork(){if(enquiryTimer)clearInterval(enquiryTimer);enquiryTimer=null;}
async function exclusiveProfileOperation<T>(operation:()=>Promise<T>){if(profileOperation)throw new Error("Another database operation is already running.");profileOperation=true;try{return await operation();}finally{profileOperation=false;}}
function registerIpc(){
  ipcMain.handle("enquiries:email",async(_e,id)=>{const detail=await enquiryDetail(z.string().uuid().parse(id));if(!detail?.customer.email)throw new Error("This customer does not have an email address.");return shell.openExternal(`mailto:${encodeURIComponent(detail.customer.email)}?subject=${encodeURIComponent(`Gruhswad enquiry ${detail.reference}`)}`)});
  ipcMain.handle("dashboard",(_e,range:DateRange)=>dashboard(range));
  ipcMain.handle("orders:list",(_e,range?:DateRange)=>listOrders(range));ipcMain.handle("orders:unified",(_e,input)=>listUnifiedOrders(unifiedOrderQuerySchema.parse(input)));ipcMain.handle("orders:detail",(_e,kind,id)=>unifiedOrderDetail(z.enum(["online","manual"]).parse(kind),z.string().uuid().parse(id)));ipcMain.handle("orders:sources",()=>orderingSources()); ipcMain.handle("orders:save",(_e,input)=>{const value=orderInputSchema.parse(input);if(!validOrderingSource(value.source,value.id))throw new Error("Choose an available ordering source.");return saveOrder(value);}); ipcMain.handle("orders:status",(_e,id,status,reason)=>updateOrderStatus(z.string().uuid().parse(id),orderStatusSchema.parse(status),z.string().trim().min(3).max(500).optional().parse(reason))); ipcMain.handle("orders:payment",(_e,input)=>addPayment(paymentInputSchema.parse(input)));
  ipcMain.handle("inventory:list",()=>listStock());ipcMain.handle("inventory:save",(_e,input)=>saveStockItem(stockItemInputSchema.parse(input)));ipcMain.handle("inventory:ledger",(_e,id)=>stockLedger(z.string().uuid().optional().parse(id)));ipcMain.handle("inventory:adjust",(_e,input)=>adjustStock(stockAdjustmentSchema.parse(input)));ipcMain.handle("inventory:purchase",(_e,input)=>receiveStock(purchaseInputSchema.parse(input)));ipcMain.handle("inventory:alerts",()=>stockAlerts());
  ipcMain.handle("recipes:list",(_e,archived)=>listRecipes(z.boolean().default(false).parse(archived)));ipcMain.handle("recipes:save",(_e,input)=>saveRecipe(recipeInputSchema.parse(input)));ipcMain.handle("recipes:link-catalog",(_e,itemId,recipeId)=>linkCatalogRecipe(z.string().parse(itemId),z.string().uuid().nullable().parse(recipeId)));ipcMain.handle("recipes:embed",(_e,id)=>youtubeEmbedUrl(z.string().regex(YOUTUBE_ID).parse(id)));ipcMain.handle("recipes:open-video",(_e,id)=>shell.openExternal(youtubeDisplayUrl(z.string().regex(YOUTUBE_ID).parse(id))));
  ipcMain.handle("tiffin:list",()=>listTiffinPlans());ipcMain.handle("tiffin:save",(_e,input)=>saveTiffinPlan(tiffinPlanInputSchema.parse(input)));ipcMain.handle("tiffin:generate",(_e,id)=>generateTiffinCycle(z.string().uuid().parse(id)));
  ipcMain.handle("expenses:scan-receipt",()=>exclusiveProfileOperation(chooseAndReadReceipt));ipcMain.handle("expenses:save-receipt",(_e,input)=>saveReceiptExpense(receiptExpenseInputSchema.parse(input)));ipcMain.handle("expenses:receipt",(_e,id)=>receiptForExpense(z.string().uuid().parse(id)));ipcMain.handle("expenses:open-receipt",(_e,id)=>openReceipt(z.string().uuid().parse(id)));
  ipcMain.handle("customers:list",(_e,query,includeArchived)=>listCustomers(z.string().max(120).default("").parse(query),z.boolean().default(false).parse(includeArchived)));ipcMain.handle("customers:save",(_e,input)=>saveCustomer(customerInputSchema.parse(input)));ipcMain.handle("customers:archive",(_e,id,archived)=>archiveCustomer(z.string().uuid().parse(id),z.boolean().parse(archived)));ipcMain.handle("customers:whatsapp",(_e,id)=>{const customer=customerContact(z.string().uuid().parse(id)),digits=customer.phone.replace(/\D/g,"");return shell.openExternal(`https://wa.me/${digits}`);});ipcMain.handle("customers:email",(_e,id)=>{const customer=customerContact(z.string().uuid().parse(id));if(!customer.email)throw new Error("This customer does not have an email address.");return shell.openExternal(`mailto:${encodeURIComponent(customer.email)}`);});
  ipcMain.handle("expenses:list",(_e,range?:DateRange)=>listExpenses(range)); ipcMain.handle("expenses:save",(_e,input)=>saveExpense(expenseInputSchema.parse(input))); ipcMain.handle("expenses:remove",(_e,id)=>removeExpense(id));
  ipcMain.handle("catalog:get",()=>getCatalog());ipcMain.handle("catalog:save",(_e,input)=>{const item=catalogItemSchema.parse(input);validateCatalogItemReferences(item);saveCatalogItem(item);saveCatalogItemCompatibility(item.id,item.webCompatible);});ipcMain.handle("catalog:archive",(_e,id,archived)=>archiveCatalogItem(String(id),Boolean(archived)));ipcMain.handle("catalog:export-pdf",()=>exportMenuPdf());ipcMain.handle("catalog:export-images",()=>exportMasterMenuImages());ipcMain.handle("catalog:preview-images",()=>previewMasterMenuImages());
  const imageSelectionSchema=z.discriminatedUnion("kind",[z.object({kind:z.literal("unchanged")}),z.object({kind:z.literal("placeholder")}),z.object({kind:z.literal("asset"),filename:z.string().regex(/^[^\\/:*?\"<>|]+\.(?:jpe?g|png|webp)$/i)}),z.object({kind:z.literal("browse"),token:z.string().uuid()})]);ipcMain.handle("catalog:image-assets",()=>packagedCatalogAssets());ipcMain.handle("catalog:choose-image",()=>chooseCatalogImage());ipcMain.handle("catalog:save-with-image",(_e,input,selection)=>saveCatalogItemWithImage(catalogItemSchema.parse(input),imageSelectionSchema.parse(selection)));
  ipcMain.handle("catalog:category-save",(_e,input)=>saveCatalogCategory(catalogCategorySchema.parse(input)));ipcMain.handle("catalog:category-active",(_e,id,active)=>setCatalogCategoryActive(String(id),Boolean(active)));
  ipcMain.handle("operations:get",()=>getRuntimeConfig());ipcMain.handle("operations:save",(_e,input)=>saveRuntimeConfig(runtimeConfigSchema.parse(input)));
  ipcMain.handle("enquiries:list",(_e,input)=>listEnquiries(z.object({query:z.string().max(120),type:z.enum(["all","party","bulk","tiffin"]),status:z.enum(["all","new","contacted","quoted","converted","closed"]),from:z.string(),to:z.string()}).parse(input)));ipcMain.handle("enquiries:count",()=>newEnquiryCount());ipcMain.handle("enquiries:status",(_e,id,status)=>{const next=z.enum(["new","contacted","quoted","converted","closed"]).parse(status);if(next==="converted")throw new Error("Use the enquiry conversion action to create the confirmed order or Tiffin plan.");return updateEnquiryStatus(z.string().uuid().parse(id),next)});
  ipcMain.handle("enquiries:convert-order",async(_e,id,input)=>{const enquiryId=z.string().uuid().parse(id),detail=await enquiryDetail(enquiryId);if(!detail||detail.type==="tiffin")throw new Error("Choose a Party or Bulk enquiry.");const existing=rawDatabase().prepare("SELECT id,order_number,enquiry_sync_pending FROM orders WHERE enquiry_id=?").get(enquiryId) as any;if(existing)return{orderId:existing.id,reference:existing.order_number,syncPending:Boolean(existing.enquiry_sync_pending)};const value=orderInputSchema.parse({...input,enquiryId,enquiryReference:detail.reference,serviceType:detail.type,status:"confirmed"}),orderId=saveOrder(value),row=rawDatabase().prepare("SELECT order_number FROM orders WHERE id=?").get(orderId) as any;let syncPending=false;try{await markEnquiryConverted(enquiryId,row.order_number)}catch{syncPending=true;rawDatabase().prepare("UPDATE orders SET enquiry_sync_pending=1 WHERE id=?").run(orderId)}return{orderId,reference:row.order_number,syncPending};});
  ipcMain.handle("enquiries:convert-tiffin",async(_e,id,input)=>{const enquiryId=z.string().uuid().parse(id),detail=await enquiryDetail(enquiryId);if(!detail||detail.type!=="tiffin")throw new Error("Choose a Tiffin enquiry.");const existing=rawDatabase().prepare("SELECT id,reference,enquiry_sync_pending FROM tiffin_plans WHERE enquiry_id=?").get(enquiryId) as any;if(existing)return{planId:existing.id,reference:existing.reference,syncPending:Boolean(existing.enquiry_sync_pending)};const planId=saveTiffinPlan(tiffinPlanInputSchema.parse({...input,enquiryId,enquiryReference:detail.reference,status:"active"})),row=rawDatabase().prepare("SELECT reference FROM tiffin_plans WHERE id=?").get(planId) as any;let syncPending=false;try{await markEnquiryConverted(enquiryId,row.reference)}catch{syncPending=true;rawDatabase().prepare("UPDATE tiffin_plans SET enquiry_sync_pending=1 WHERE id=?").run(planId)}return{planId,reference:row.reference,syncPending};});
  ipcMain.handle("enquiries:retry-conversion",async(_e,id)=>{const enquiryId=z.string().uuid().parse(id),order=rawDatabase().prepare("SELECT id,order_number FROM orders WHERE enquiry_id=?").get(enquiryId) as any,plan=rawDatabase().prepare("SELECT id,reference FROM tiffin_plans WHERE enquiry_id=?").get(enquiryId) as any,reference=order?.order_number??plan?.reference;if(!reference)throw new Error("No local conversion was found.");await markEnquiryConverted(enquiryId,reference);if(order)rawDatabase().prepare("UPDATE orders SET enquiry_sync_pending=0 WHERE id=?").run(order.id);if(plan)rawDatabase().prepare("UPDATE tiffin_plans SET enquiry_sync_pending=0 WHERE id=?").run(plan.id);});
  ipcMain.handle("enquiries:detail",(_e,id)=>enquiryDetail(z.string().uuid().parse(id)));ipcMain.handle("enquiries:seen",(_e,id)=>markEnquirySeen(z.string().uuid().parse(id)));ipcMain.handle("enquiries:preference",()=>notificationPreference());ipcMain.handle("enquiries:set-preference",(_e,enabled)=>setNotificationPreference(z.boolean().parse(enabled)));ipcMain.handle("enquiries:whatsapp",async(_e,id)=>{const detail=await enquiryDetail(z.string().uuid().parse(id));if(!detail)throw new Error("Enquiry not found.");const digits=detail.customer.phone.replace(/\D/g,"");return shell.openExternal(`https://wa.me/${digits}?text=${encodeURIComponent(`Namaste ${detail.customer.name}, regarding your Gruhswad enquiry ${detail.reference}:`)}`)});ipcMain.handle("enquiries:call",async(_e,id)=>{const detail=await enquiryDetail(z.string().uuid().parse(id));if(!detail)throw new Error("Enquiry not found.");return shell.openExternal(`tel:${detail.customer.phone}`)});ipcMain.handle("enquiries:copy",async(_e,id)=>{const detail=await enquiryDetail(z.string().uuid().parse(id));if(!detail)throw new Error("Enquiry not found.");clipboard.writeText(detail.reference)});
  ipcMain.handle("enquiries:notification-status",()=>({supported:Notification.isSupported(),enabled:notificationPreference(),packaged:app.isPackaged,platform:process.platform}));
  ipcMain.handle("enquiries:test-notification",()=>showNativeNotification("Gruhswad enquiry notifications","Test successful. New website enquiries can appear here."));
  ipcMain.handle("menu:catalog",()=>getCatalog()); ipcMain.handle("menu:history",()=>publicationHistory());ipcMain.handle("menu:current",()=>getCurrentPublication()); ipcMain.handle("menu:publish",(_e,input)=>publishToGruhswad(publicationSchema.parse(input)));ipcMain.handle("menu:export-pdf",()=>exportOneDayMenuPdf());ipcMain.handle("menu:export-photo-pdf",()=>exportPhotoOneDayMenuPdf());ipcMain.handle("menu:export-images",()=>exportOneDayMenuImages());ipcMain.handle("menu:preview-images",()=>previewOneDayMenuImages());ipcMain.handle("menu:share-whatsapp",()=>shareOneDayMenuOnWhatsApp());
  const previewIndex=z.number().int().nonnegative();ipcMain.handle("images:preview",(_e,index)=>latestImageDataUrl(previewIndex.parse(index)));ipcMain.handle("images:open",(_e,index)=>openLatestImage(previewIndex.parse(index)));ipcMain.handle("images:show-in-folder",(_e,index)=>showLatestImageInFolder(previewIndex.parse(index)));
  ipcMain.handle("cloud-orders:list",(_e,query)=>listCloudOrders(String(query??"")));ipcMain.handle("cloud-orders:detail",(_e,id)=>cloudOrderDetail(String(id)));ipcMain.handle("cloud-orders:status",(_e,id,status)=>updateCloudOrderStatus(String(id),cloudOrderStatusSchema.parse(status)));
  ipcMain.handle("sync:status",()=>syncStatus());ipcMain.handle("sync:attention",()=>syncAttention());ipcMain.handle("sync:preview-pull",()=>previewPull());ipcMain.handle("sync:pull",()=>exclusiveProfileOperation(pullFromNeon));ipcMain.handle("sync:preview-push",()=>previewPush());ipcMain.handle("sync:push",()=>exclusiveProfileOperation(pushToNeon));ipcMain.handle("sync:conflicts",()=>listConflicts());ipcMain.handle("sync:resolve",(_e,id,resolution)=>resolveConflict(String(id),resolution));ipcMain.handle("sync:history",()=>syncHistory());
  ipcMain.handle("menu-publishing:status",()=>menuImagePublicationStatus());ipcMain.handle("menu-publishing:publish",()=>publishMenuImages());
  ipcMain.handle("external:open-alpha-initiatives",()=>shell.openExternal("https://alphinitive.vercel.app/"));
  ipcMain.handle("inbox:list",()=>listInbox()); ipcMain.handle("inbox:sync",()=>syncInbox());
  ipcMain.handle("settings:get",()=>({...getSettings(),gcsBucket:getSettings().gcsBucket||"fb-image-store",hasNeonUrl:Boolean(loadSecrets().neonDatabaseUrl),hasInboxToken:Boolean(loadSecrets().inboxToken),hasGcsCredentials:Boolean(loadStoredSecrets().gcsServiceAccountJson),localProfiles:localProfiles(),databaseConnection:databaseConnectionInfo()})); ipcMain.handle("settings:set",(_e,values,secrets)=>{const parsed=z.object({webhookUrl:z.string().default(""),gcsBucket:z.string().regex(/^[a-z0-9][a-z0-9._-]{1,220}[a-z0-9]$/).default("fb-image-store")}).parse(values);setSettings(parsed);if(secrets){const allowed=z.object({neonDatabaseUrl:z.string().optional(),inboxToken:z.string().optional()}).parse(secrets),next={...loadStoredSecrets()};for(const [key,value] of Object.entries(allowed))if(value?.trim())next[key]=value.trim();saveSecrets(next);}});ipcMain.handle("settings:import-gcs",()=>importGcsCredentials()); ipcMain.handle("settings:backup",()=>backupDatabase()); ipcMain.handle("settings:restore",()=>restoreDatabase());ipcMain.handle("settings:portable-summary",()=>portableBackupSummary(appDataPath));ipcMain.handle("settings:portable-archive-unreadable",(_e,profile)=>archiveUnreadableProfileCredentials(appDataPath,z.enum(["production","intensive-testing"]).parse(profile)));ipcMain.handle("settings:portable-export",(_e,password)=>exclusiveProfileOperation(()=>exportPortableBackup(appDataPath,z.string().min(10).max(200).parse(password),portableEnvironment())));ipcMain.handle("settings:portable-import",async(_e,password)=>{const value=await exclusiveProfileOperation(()=>inspectAndStagePortableBackup(appDataPath,z.string().min(10).max(200).parse(password)));if(value)setTimeout(()=>{stopBackgroundWork();app.relaunch();app.exit(0)},500);return value});
  ipcMain.handle("settings:clone-test-database",async()=>{if(activeProfile!=="production")throw new Error("Switch to Production before refreshing the test database.");if(enquiryPolling)throw new Error("Wait for the current enquiry operation to finish.");return exclusiveProfileOperation(async()=>{const test=localProfiles().profiles.find(profile=>profile.id==="intensive-testing")!;return cloneDatabase(rawDatabase(),test.databasePath);});});
  ipcMain.handle("settings:switch-profile",(_e,profile)=>{const target=z.enum(["production","intensive-testing"]).parse(profile);const info=localProfiles().profiles.find(item=>item.id===target)!;if(target==="intensive-testing"&&!info.exists)throw new Error("Create the intensive-testing database copy first.");if(profileOperation||enquiryPolling)throw new Error("Wait for the current database or enquiry operation to finish.");stopBackgroundWork();writeSelectedProfile(localProfiles().selectionPath,target);allowCloseOnce=true;app.relaunch();app.exit(0);});
  ipcMain.handle("reports:export",(_e,kind,range)=>exportCsv(kind,range)); ipcMain.handle("updates:check",()=>autoUpdater.checkForUpdates()); ipcMain.handle("updates:install",()=>autoUpdater.quitAndInstall());
}
async function focusEnquiry(detail:Awaited<ReturnType<typeof pollEnquiries>>["items"][number]){if(!window||window.isDestroyed())return;if(window.isMinimized())window.restore();window.show();window.focus();const seen=await markEnquirySeen(detail.id);if(seen)window.webContents.send("enquiries:open",seen)}
function showNativeNotification(title:string,body:string,onClick?:()=>void):Promise<NotificationResult>{
  if(!Notification.isSupported())return Promise.resolve({outcome:"unsupported"});
  return new Promise(resolve=>{let settled=false;const finish=(outcome:NotificationResult["outcome"])=>{if(settled)return;settled=true;resolve({outcome})};try{const notification=new Notification({title,body});activeNotifications.add(notification);notification.once("show",()=>finish("shown"));notification.once("failed",()=>{activeNotifications.delete(notification);finish("failed")});notification.on("click",()=>{onClick?.();activeNotifications.delete(notification)});notification.once("close",()=>activeNotifications.delete(notification));notification.show();setTimeout(()=>finish("failed"),3000)}catch{finish("failed")}})
}
async function runEnquiryPoll(){if(enquiryPolling)return;enquiryPolling=true;try{const result=await pollEnquiries();const content=enquiryNotificationContent(result.items);if(content){let notification:"shown"|"disabled"|"unsupported"|"failed"="disabled";if(result.enabled)notification=(await showNativeNotification(content.title,content.body,()=>void focusEnquiry(content.target))).outcome;window?.webContents.send("enquiries:arrived",{items:result.items,notification})}}catch{/* Retry on the next poll. */}finally{enquiryPolling=false}}
function startEnquiryPolling(){if(enquiryTimer)return;void runEnquiryPoll();enquiryTimer=setInterval(()=>void runEnquiryPoll(),60_000)}
async function startStartupPull(){let configured=true;try{configured=databaseConnection().configured;}catch{}if(!configured){window?.webContents.send("sync:startup-pull-settled");return;}try{await pullFromNeon();window?.webContents.send("sync:startup-pull-complete");}catch{/* Startup remains silent; the failed run is visible in Sync Centre. */}finally{window?.webContents.send("sync:startup-pull-settled");}}
async function showExitWarning(attention:ReturnType<typeof syncAttention>|null){if(!window||window.isDestroyed())return;const copy=exitWarningCopy(attention),result=await dialog.showMessageBox(window,{type:"warning",title:copy.title,message:copy.message,detail:copy.detail,buttons:["Go to Sync Centre","Exit Anyway"],defaultId:0,cancelId:0,noLink:true});if(!window||window.isDestroyed())return;if(result.response===1){allowCloseOnce=true;window.close();return;}if(window.isMinimized())window.restore();window.show();window.focus();window.webContents.send("sync:navigate");}
function guardWindowClose(target:BrowserWindow){target.on("close",(event)=>{if(allowCloseOnce){allowCloseOnce=false;return;}if(exitDialogOpen){event.preventDefault();return;}let attention:ReturnType<typeof syncAttention>|null=null;try{attention=syncAttention();if(!attention.requiresAttention)return;}catch{/* The warning explains that status could not be verified. */}event.preventDefault();exitDialogOpen=true;void showExitWarning(attention).finally(()=>{exitDialogOpen=false;});});}
function createWindow(){window=new BrowserWindow({width:1440,height:920,minWidth:1080,minHeight:700,backgroundColor:"#fff8f1",webPreferences:{preload:join(__dirname,"../preload/index.cjs"),nodeIntegration:false,contextIsolation:true,sandbox:true}});guardWindowClose(window);window.webContents.once("did-finish-load",()=>{void startStartupPull().finally(startEnquiryPolling);});const devUrl=process.env.ELECTRON_RENDERER_URL;if(!app.isPackaged&&devUrl)window.loadURL(devUrl);else window.loadFile(join(__dirname,"../renderer/index.html"));}
app.whenReady().then(async()=>{if(helperRequest){await runProfileSecretHelper(helperRequest[0],helperRequest[1],helperRequest[2]);return;}app.setAppUserModelId("in.gruhswad.admin");await protocol.handle("catalog-image",(request)=>catalogImageResponse(request.url));const databasePath=join(app.getPath("userData"),"gruhswad-admin.db"),pendingPath=join(app.getPath("userData"),"restore-pending.db");if(existsSync(pendingPath)){rmSync(databasePath,{force:true});renameSync(pendingPath,databasePath);}initializeDatabase(databasePath,app.isPackaged?join(process.resourcesPath,"drizzle"):join(process.cwd(),"drizzle"));if(process.env.GRUHSWAD_SYNC_SMOKE==="1"){try{const result=await pullFromNeon();writeFileSync(join(app.getPath("userData"),"sync-smoke.json"),JSON.stringify({ok:true,result}));}catch(error){writeFileSync(join(app.getPath("userData"),"sync-smoke.json"),JSON.stringify({ok:false,error:String(error)}));process.exitCode=1;}finally{app.quit();}return;}registerIpc();createWindow(); if(app.isPackaged)autoUpdater.checkForUpdatesAndNotify();});
for(const event of ["checking-for-update","update-available","update-not-available","download-progress","update-downloaded","error"] as const) autoUpdater.on(event,(value:any)=>window?.webContents.send("updates:status",event==="download-progress"?`Downloading ${Math.round(value.percent)}%`:event));
app.on("before-quit",()=>{if(enquiryTimer)clearInterval(enquiryTimer);enquiryTimer=null;cleanupLatestImagePreview();});app.on("window-all-closed",()=>{if(process.platform!=="darwin")app.quit();}); app.on("activate",()=>{if(BrowserWindow.getAllWindows().length===0)createWindow();});
