import { join } from "node:path";
import { existsSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { app, BrowserWindow, dialog, ipcMain, protocol, shell } from "electron";
import updater from "electron-updater";
import { catalogCategorySchema, catalogItemSchema, cloudOrderStatusSchema, expenseInputSchema, orderInputSchema, orderStatusSchema, paymentInputSchema, publicationSchema, runtimeConfigSchema, type DateRange } from "../shared/contracts";
import { addPayment, archiveCatalogItem, cloudOrderDetail, dashboard, getCatalog, getCurrentPublication, getRuntimeConfig, getSettings, initializeDatabase, listCloudOrders, listExpenses, listInbox, listOrders, publicationHistory, removeExpense, saveCatalogCategory, saveCatalogItem, saveCatalogItemCompatibility, saveExpense, saveOrder, saveRuntimeConfig, setCatalogCategoryActive, setSettings, updateCloudOrderStatus, updateOrderStatus, validateCatalogItemReferences } from "./database";
import { backupDatabase, databaseConnection, exportCsv, importGcsCredentials, loadSecrets, loadStoredSecrets, publishToGruhswad, restoreDatabase, saveSecrets, syncInbox } from "./services";
import { listConflicts, previewPull, previewPush, pullFromNeon, pushToNeon, resolveConflict, syncAttention, syncHistory, syncStatus } from "./sync-engine";
import { exitWarningCopy } from "../shared/sync-attention";
import { exportMenuPdf } from "./menu-pdf";
import { exportOneDayMenuPdf } from "./one-day-menu-pdf";
import { exportPhotoOneDayMenuPdf } from "./one-day-menu-photo-pdf";
import { exportMasterMenuImages, exportOneDayMenuImages, previewMasterMenuImages, previewOneDayMenuImages } from "./template-menu-images";
import { cleanupLatestImagePreview, latestImageDataUrl, openLatestImage, showLatestImageInFolder } from "./image-renderer";
import { shareOneDayMenuOnWhatsApp } from "./whatsapp-menu";
import { menuImagePublicationStatus, publishMenuImages } from "./menu-publishing";
import { z } from "zod";
import { catalogImageResponse, chooseCatalogImage, packagedCatalogAssets, saveCatalogItemWithImage } from "./catalog-images";

let window:BrowserWindow|null=null;
protocol.registerSchemesAsPrivileged([{scheme:"catalog-image",privileges:{standard:true,secure:true,supportFetchAPI:true}}]);
let exitDialogOpen=false;
let allowCloseOnce=false;
const { autoUpdater } = updater;
if(process.env.GRUHSWAD_TEST_USER_DATA)app.setPath("userData",process.env.GRUHSWAD_TEST_USER_DATA);
function registerIpc(){
  ipcMain.handle("dashboard",(_e,range:DateRange)=>dashboard(range));
  ipcMain.handle("orders:list",(_e,range?:DateRange)=>listOrders(range)); ipcMain.handle("orders:save",(_e,input)=>saveOrder(orderInputSchema.parse(input))); ipcMain.handle("orders:status",(_e,id,status)=>updateOrderStatus(id,orderStatusSchema.parse(status))); ipcMain.handle("orders:payment",(_e,input)=>addPayment(paymentInputSchema.parse(input)));
  ipcMain.handle("expenses:list",(_e,range?:DateRange)=>listExpenses(range)); ipcMain.handle("expenses:save",(_e,input)=>saveExpense(expenseInputSchema.parse(input))); ipcMain.handle("expenses:remove",(_e,id)=>removeExpense(id));
  ipcMain.handle("catalog:get",()=>getCatalog());ipcMain.handle("catalog:save",(_e,input)=>{const item=catalogItemSchema.parse(input);validateCatalogItemReferences(item);saveCatalogItem(item);saveCatalogItemCompatibility(item.id,item.webCompatible);});ipcMain.handle("catalog:archive",(_e,id,archived)=>archiveCatalogItem(String(id),Boolean(archived)));ipcMain.handle("catalog:export-pdf",()=>exportMenuPdf());ipcMain.handle("catalog:export-images",()=>exportMasterMenuImages());ipcMain.handle("catalog:preview-images",()=>previewMasterMenuImages());
  const imageSelectionSchema=z.discriminatedUnion("kind",[z.object({kind:z.literal("unchanged")}),z.object({kind:z.literal("placeholder")}),z.object({kind:z.literal("asset"),filename:z.string().regex(/^[^\\/:*?\"<>|]+\.(?:jpe?g|png|webp)$/i)}),z.object({kind:z.literal("browse"),token:z.string().uuid()})]);ipcMain.handle("catalog:image-assets",()=>packagedCatalogAssets());ipcMain.handle("catalog:choose-image",()=>chooseCatalogImage());ipcMain.handle("catalog:save-with-image",(_e,input,selection)=>saveCatalogItemWithImage(catalogItemSchema.parse(input),imageSelectionSchema.parse(selection)));
  ipcMain.handle("catalog:category-save",(_e,input)=>saveCatalogCategory(catalogCategorySchema.parse(input)));ipcMain.handle("catalog:category-active",(_e,id,active)=>setCatalogCategoryActive(String(id),Boolean(active)));
  ipcMain.handle("operations:get",()=>getRuntimeConfig());ipcMain.handle("operations:save",(_e,input)=>saveRuntimeConfig(runtimeConfigSchema.parse(input)));
  ipcMain.handle("menu:catalog",()=>getCatalog()); ipcMain.handle("menu:history",()=>publicationHistory());ipcMain.handle("menu:current",()=>getCurrentPublication()); ipcMain.handle("menu:publish",(_e,input)=>publishToGruhswad(publicationSchema.parse(input)));ipcMain.handle("menu:export-pdf",()=>exportOneDayMenuPdf());ipcMain.handle("menu:export-photo-pdf",()=>exportPhotoOneDayMenuPdf());ipcMain.handle("menu:export-images",()=>exportOneDayMenuImages());ipcMain.handle("menu:preview-images",()=>previewOneDayMenuImages());ipcMain.handle("menu:share-whatsapp",()=>shareOneDayMenuOnWhatsApp());
  const previewIndex=z.number().int().nonnegative();ipcMain.handle("images:preview",(_e,index)=>latestImageDataUrl(previewIndex.parse(index)));ipcMain.handle("images:open",(_e,index)=>openLatestImage(previewIndex.parse(index)));ipcMain.handle("images:show-in-folder",(_e,index)=>showLatestImageInFolder(previewIndex.parse(index)));
  ipcMain.handle("cloud-orders:list",(_e,query)=>listCloudOrders(String(query??"")));ipcMain.handle("cloud-orders:detail",(_e,id)=>cloudOrderDetail(String(id)));ipcMain.handle("cloud-orders:status",(_e,id,status)=>updateCloudOrderStatus(String(id),cloudOrderStatusSchema.parse(status)));
  ipcMain.handle("sync:status",()=>syncStatus());ipcMain.handle("sync:attention",()=>syncAttention());ipcMain.handle("sync:preview-pull",()=>previewPull());ipcMain.handle("sync:pull",()=>pullFromNeon());ipcMain.handle("sync:preview-push",()=>previewPush());ipcMain.handle("sync:push",()=>pushToNeon());ipcMain.handle("sync:conflicts",()=>listConflicts());ipcMain.handle("sync:resolve",(_e,id,resolution)=>resolveConflict(String(id),resolution));ipcMain.handle("sync:history",()=>syncHistory());
  ipcMain.handle("menu-publishing:status",()=>menuImagePublicationStatus());ipcMain.handle("menu-publishing:publish",()=>publishMenuImages());
  ipcMain.handle("external:open-alpha-initiatives",()=>shell.openExternal("https://alphinitive.vercel.app/"));
  ipcMain.handle("inbox:list",()=>listInbox()); ipcMain.handle("inbox:sync",()=>syncInbox());
  ipcMain.handle("settings:get",()=>({...getSettings(),gcsBucket:getSettings().gcsBucket||"fb-image-store",hasNeonUrl:Boolean(loadSecrets().neonDatabaseUrl),hasInboxToken:Boolean(loadSecrets().inboxToken),hasGcsCredentials:Boolean(loadStoredSecrets().gcsServiceAccountJson)})); ipcMain.handle("settings:set",(_e,values,secrets)=>{const parsed=z.object({webhookUrl:z.string().default(""),gcsBucket:z.string().regex(/^[a-z0-9][a-z0-9._-]{1,220}[a-z0-9]$/).default("fb-image-store")}).parse(values);setSettings(parsed);if(secrets){const allowed=z.object({neonDatabaseUrl:z.string().optional(),inboxToken:z.string().optional()}).parse(secrets),next={...loadStoredSecrets()};for(const [key,value] of Object.entries(allowed))if(value?.trim())next[key]=value.trim();saveSecrets(next);}});ipcMain.handle("settings:import-gcs",()=>importGcsCredentials()); ipcMain.handle("settings:backup",()=>backupDatabase()); ipcMain.handle("settings:restore",()=>restoreDatabase());
  ipcMain.handle("reports:export",(_e,kind,range)=>exportCsv(kind,range)); ipcMain.handle("updates:check",()=>autoUpdater.checkForUpdates()); ipcMain.handle("updates:install",()=>autoUpdater.quitAndInstall());
}
async function startStartupPull(){let configured=true;try{configured=databaseConnection().configured;}catch{}if(!configured){window?.webContents.send("sync:startup-pull-settled");return;}try{await pullFromNeon();window?.webContents.send("sync:startup-pull-complete");}catch{/* Startup remains silent; the failed run is visible in Sync Centre. */}finally{window?.webContents.send("sync:startup-pull-settled");}}
async function showExitWarning(attention:ReturnType<typeof syncAttention>|null){if(!window||window.isDestroyed())return;const copy=exitWarningCopy(attention),result=await dialog.showMessageBox(window,{type:"warning",title:copy.title,message:copy.message,detail:copy.detail,buttons:["Go to Sync Centre","Exit Anyway"],defaultId:0,cancelId:0,noLink:true});if(!window||window.isDestroyed())return;if(result.response===1){allowCloseOnce=true;window.close();return;}if(window.isMinimized())window.restore();window.show();window.focus();window.webContents.send("sync:navigate");}
function guardWindowClose(target:BrowserWindow){target.on("close",(event)=>{if(allowCloseOnce){allowCloseOnce=false;return;}if(exitDialogOpen){event.preventDefault();return;}let attention:ReturnType<typeof syncAttention>|null=null;try{attention=syncAttention();if(!attention.requiresAttention)return;}catch{/* The warning explains that status could not be verified. */}event.preventDefault();exitDialogOpen=true;void showExitWarning(attention).finally(()=>{exitDialogOpen=false;});});}
function createWindow(){window=new BrowserWindow({width:1440,height:920,minWidth:1080,minHeight:700,backgroundColor:"#fff8f1",webPreferences:{preload:join(__dirname,"../preload/index.cjs"),nodeIntegration:false,contextIsolation:true,sandbox:true}});guardWindowClose(window);window.webContents.once("did-finish-load",()=>{void startStartupPull();});const devUrl=process.env.ELECTRON_RENDERER_URL;if(!app.isPackaged&&devUrl)window.loadURL(devUrl);else window.loadFile(join(__dirname,"../renderer/index.html"));}
app.whenReady().then(async()=>{await protocol.handle("catalog-image",(request)=>catalogImageResponse(request.url));const databasePath=join(app.getPath("userData"),"gruhswad-admin.db"),pendingPath=join(app.getPath("userData"),"restore-pending.db");if(existsSync(pendingPath)){rmSync(databasePath,{force:true});renameSync(pendingPath,databasePath);}initializeDatabase(databasePath,app.isPackaged?join(process.resourcesPath,"drizzle"):join(process.cwd(),"drizzle"));if(process.env.GRUHSWAD_SYNC_SMOKE==="1"){try{const result=await pullFromNeon();writeFileSync(join(app.getPath("userData"),"sync-smoke.json"),JSON.stringify({ok:true,result}));}catch(error){writeFileSync(join(app.getPath("userData"),"sync-smoke.json"),JSON.stringify({ok:false,error:String(error)}));process.exitCode=1;}finally{app.quit();}return;}registerIpc();createWindow(); if(app.isPackaged)autoUpdater.checkForUpdatesAndNotify();});
for(const event of ["checking-for-update","update-available","update-not-available","download-progress","update-downloaded","error"] as const) autoUpdater.on(event,(value:any)=>window?.webContents.send("updates:status",event==="download-progress"?`Downloading ${Math.round(value.percent)}%`:event));
app.on("before-quit",cleanupLatestImagePreview);app.on("window-all-closed",()=>{if(process.platform!=="darwin")app.quit();}); app.on("activate",()=>{if(BrowserWindow.getAllWindows().length===0)createWindow();});
