import { createCipheriv, createDecipheriv, createHash, randomBytes, scrypt as scryptCallback } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, readdirSync, renameSync, rmSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative, sep } from "node:path";
import { promisify } from "node:util";
import { spawn } from "node:child_process";
import { fileURLToPath } from "node:url";
import Database from "better-sqlite3";
import { app, dialog, safeStorage } from "electron";
import { unzipSync, zipSync } from "fflate";
import { profileState, readSelectedProfile, writeSelectedProfile, type LocalDataProfile } from "./local-data-profiles";
import { rawDatabase } from "./database";

const scrypt=promisify(scryptCallback),MAGIC="GRUHSWAD_PORTABLE_BACKUP",VERSION=1,PENDING_DIRECTORY="gruhswad-admin-portable-restore-pending";
const durableDirectories=["receipts"] as const;
export const PORTABLE_SETTINGS_INVENTORY={version:1,sqlite:["settings","app_settings","notification_state","sync_state","sync_runs","sync_conflicts"],secrets:["neonDatabaseUrl","inboxToken","gcsServiceAccountJson"],environment:["APP_ENV","DATABASE_URL_LOCAL","DATABASE_URL_PROD","DATABASE_URL"]} as const;

type Manifest={magic:typeof MAGIC;version:number;createdAt:string;appVersion:string;activeProfile:LocalDataProfile;profiles:Array<{id:LocalDataProfile;database:boolean;secrets:boolean;attachments:number}>;settingsInventory:typeof PORTABLE_SETTINGS_INVENTORY;environment:Record<string,string>;checksums:Record<string,string>};
type Envelope={magic:typeof MAGIC;version:number;kdf:"scrypt";cipher:"aes-256-gcm";salt:string;iv:string;tag:string;ciphertext:string};
const checksum=(value:Uint8Array)=>createHash("sha256").update(value).digest("hex");
const safeEntry=(name:string)=>!name.startsWith("/")&&!name.includes("\\")&&!name.split("/").includes("..");
function files(directory:string){const result:string[]=[];if(!existsSync(directory))return result;for(const name of readdirSync(directory)){const path=join(directory,name),stats=statSync(path);if(stats.isDirectory())result.push(...files(path));else if(stats.isFile())result.push(path)}return result}
function decryptSecrets(path:string){if(!existsSync(path))return{};try{return JSON.parse(safeStorage.decryptString(readFileSync(path))) as Record<string,string>}catch{throw new Error("Saved credentials cannot be decrypted on this Windows account.")}}
function profileSecrets(mode:"decrypt"|"encrypt",userDataPath:string,outputPath?:string,values?:Record<string,string>){return new Promise<Record<string,string>>((resolve,reject)=>{const environment={...process.env};delete environment.ELECTRON_RUN_AS_NODE;const args=app.isPackaged?["--gruhswad-profile-secret-helper",mode,userDataPath,...(outputPath?[outputPath]:[])]:[join(dirname(fileURLToPath(import.meta.url)),"profile-secret-helper.js"),mode,userDataPath,...(outputPath?[outputPath]:[])],child=spawn(process.execPath,args,{env:environment,stdio:["pipe","pipe","pipe"],windowsHide:true});let stdout="";child.stdout.setEncoding("utf8");child.stdout.on("data",chunk=>{stdout+=chunk});child.on("error",()=>reject(new Error("The profile credential helper could not start.")));child.on("exit",code=>{if(code!==0)return reject(new Error("Electron could not process credentials for the selected local-data profile."));try{resolve(mode==="decrypt"?JSON.parse(stdout):{})}catch{reject(new Error("Saved credentials are invalid."))}});child.stdin.end(mode==="encrypt"?JSON.stringify(values??{}):undefined)})}
async function key(password:string,salt:Buffer){if(password.length<10)throw new Error("Use a backup password containing at least 10 characters.");return await scrypt(password,salt,32) as Buffer}
async function encrypt(payload:Uint8Array,password:string){const salt=randomBytes(16),iv=randomBytes(12),cipher=createCipheriv("aes-256-gcm",await key(password,salt),iv),ciphertext=Buffer.concat([cipher.update(payload),cipher.final()]);return Buffer.from(JSON.stringify({magic:MAGIC,version:VERSION,kdf:"scrypt",cipher:"aes-256-gcm",salt:salt.toString("base64"),iv:iv.toString("base64"),tag:cipher.getAuthTag().toString("base64"),ciphertext:ciphertext.toString("base64")} satisfies Envelope))}
async function decrypt(payload:Buffer,password:string){let envelope:Envelope;try{envelope=JSON.parse(payload.toString("utf8"))}catch{throw new Error("This is not a Gruhswad portable backup.")}if(envelope.magic!==MAGIC||envelope.version!==VERSION||envelope.kdf!=="scrypt"||envelope.cipher!=="aes-256-gcm")throw new Error("This portable backup version is not supported.");try{const decipher=createDecipheriv("aes-256-gcm",await key(password,Buffer.from(envelope.salt,"base64")),Buffer.from(envelope.iv,"base64"));decipher.setAuthTag(Buffer.from(envelope.tag,"base64"));return Buffer.concat([decipher.update(Buffer.from(envelope.ciphertext,"base64")),decipher.final()])}catch{throw new Error("The backup password is incorrect or the backup is damaged.")}}
function validateDatabase(path:string){let db:Database.Database|undefined;try{db=new Database(path,{readonly:true});if(db.pragma("integrity_check",{simple:true})!=="ok")throw new Error("SQLite integrity validation failed.");if(!db.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name='schema_migrations'").get())throw new Error("Migration history is missing.")}finally{db?.close()}}

export function portableBackupSummary(appDataPath:string){const active=readSelectedProfile(join(appDataPath,"gruhswad-admin-desktop-profile.json")),state=profileState(appDataPath,active);return{activeProfile:active,profiles:state.profiles.map(profile=>{const included=existsSync(join(profile.userDataPath,"secrets.bin"));return{id:profile.id,label:profile.label,database:profile.exists,settings:profile.exists,secrets:included,credentialState:included?"included":"missing",attachments:durableDirectories.flatMap(name=>files(join(profile.userDataPath,name))).length}}),settingsGroups:["Complete SQLite settings","Connection credentials","Environment selection","Profile selection","Receipt attachments"]}}

export function archiveUnreadableProfileCredentials(appDataPath:string,profileId:LocalDataProfile){const state=profileState(appDataPath,readSelectedProfile(join(appDataPath,"gruhswad-admin-desktop-profile.json"))),profile=state.profiles.find(value=>value.id===profileId);if(!profile)throw new Error("The selected local-data profile is not supported.");const path=join(profile.userDataPath,"secrets.bin");if(!existsSync(path))return false;try{decryptSecrets(path);throw new Error(`${profile.label} credentials are readable and must not be archived.`)}catch(error){if(error instanceof Error&&error.message.includes("must not be archived"))throw error}const stamp=new Date().toISOString().replace(/[:.]/g,"-");renameSync(path,`${path}.unreadable-${stamp}`);return true}

export async function exportPortableBackup(appDataPath:string,password:string,environment:Record<string,string>){if(!safeStorage.isEncryptionAvailable())throw new Error("OS encryption is unavailable, so credentials cannot be exported safely.");const summary=portableBackupSummary(appDataPath),state=profileState(appDataPath,summary.activeProfile),temporary=join(appDataPath,`gruhswad-portable-export-${process.pid}`),entries:Record<string,Uint8Array>={},profiles:Manifest["profiles"]=[];rmSync(temporary,{recursive:true,force:true});mkdirSync(temporary,{recursive:true});try{for(const profile of state.profiles){let database=false,secrets=false,attachments=0;if(profile.exists){const target=join(temporary,`${profile.id}.db`),source=profile.id===summary.activeProfile?rawDatabase():new Database(profile.databasePath);try{await source.backup(target)}finally{if(profile.id!==summary.activeProfile)source.close()}validateDatabase(target);entries[`profiles/${profile.id}/database.db`]=readFileSync(target);database=true}const secretPath=join(profile.userDataPath,"secrets.bin");if(existsSync(secretPath)){entries[`profiles/${profile.id}/secrets.json`]=Buffer.from(JSON.stringify(await profileSecrets("decrypt",profile.userDataPath)));secrets=true}for(const directory of durableDirectories){for(const path of files(join(profile.userDataPath,directory))){const name=`profiles/${profile.id}/durable/${relative(profile.userDataPath,path).split(sep).join("/")}`;entries[name]=readFileSync(path);attachments++}}profiles.push({id:profile.id,database,secrets,attachments})}const manifest:Manifest={magic:MAGIC,version:VERSION,createdAt:new Date().toISOString(),appVersion:app.getVersion(),activeProfile:summary.activeProfile,profiles,settingsInventory:PORTABLE_SETTINGS_INVENTORY,environment:Object.fromEntries(PORTABLE_SETTINGS_INVENTORY.environment.map(name=>[name,environment[name]??""]).filter(([,value])=>value)),checksums:{}};for(const[name,value]of Object.entries(entries))manifest.checksums[name]=checksum(value);entries["manifest.json"]=Buffer.from(JSON.stringify(manifest));const result=await dialog.showSaveDialog({defaultPath:`gruhswad-complete-${new Date().toISOString().slice(0,10)}.gswportable`,filters:[{name:"Gruhswad portable backup",extensions:["gswportable"]}]});if(result.canceled||!result.filePath)return null;writeFileSync(result.filePath,await encrypt(zipSync(entries,{level:6}),password));return result.filePath}finally{rmSync(temporary,{recursive:true,force:true})}}

export async function inspectAndStagePortableBackup(appDataPath:string,password:string){if(!safeStorage.isEncryptionAvailable())throw new Error("OS encryption is unavailable, so credentials cannot be restored safely.");const result=await dialog.showOpenDialog({filters:[{name:"Gruhswad portable backup",extensions:["gswportable"]}],properties:["openFile"]});if(result.canceled||!result.filePaths[0])return null;const archive=unzipSync(await decrypt(readFileSync(result.filePaths[0]),password));for(const name of Object.keys(archive))if(!safeEntry(name))throw new Error("The backup contains an unsafe file path.");let manifest:Manifest;try{manifest=JSON.parse(Buffer.from(archive["manifest.json"]).toString("utf8"))}catch{throw new Error("The backup manifest is missing or invalid.")}if(manifest.magic!==MAGIC||manifest.version!==VERSION)throw new Error("This portable backup version is not supported.");for(const[name,expected]of Object.entries(manifest.checksums)){const value=archive[name];if(!value||checksum(value)!==expected)throw new Error(`Backup checksum validation failed for ${name}.`)}const pending=join(appDataPath,PENDING_DIRECTORY),state=profileState(appDataPath,manifest.activeProfile);rmSync(pending,{recursive:true,force:true});mkdirSync(pending,{recursive:true});try{for(const profile of manifest.profiles){const prefix=`profiles/${profile.id}/`,database=archive[`${prefix}database.db`],targetProfile=state.profiles.find(value=>value.id===profile.id);if(!targetProfile)throw new Error("The backup contains an unsupported profile.");if(database){const path=join(pending,profile.id,"gruhswad-admin.db");mkdirSync(dirname(path),{recursive:true});writeFileSync(path,database);validateDatabase(path)}const secrets=archive[`${prefix}secrets.json`];if(secrets){const values=JSON.parse(Buffer.from(secrets).toString("utf8")) as Record<string,string>,path=join(pending,profile.id,"secrets.bin");mkdirSync(dirname(path),{recursive:true});await profileSecrets("encrypt",targetProfile.userDataPath,path,values)}for(const[name,value]of Object.entries(archive)){if(name.startsWith(`${prefix}durable/`)){const relativeName=name.slice(`${prefix}durable/`.length);if(!safeEntry(relativeName))throw new Error("The backup contains an unsafe attachment path.");const path=join(pending,profile.id,relativeName);mkdirSync(dirname(path),{recursive:true});writeFileSync(path,value)}}}writeFileSync(join(pending,"managed-environment.json"),JSON.stringify(manifest.environment,null,2));writeFileSync(join(pending,"pending.json"),JSON.stringify({activeProfile:manifest.activeProfile,createdAt:manifest.createdAt,appVersion:manifest.appVersion,profiles:manifest.profiles},null,2));return{activeProfile:manifest.activeProfile,createdAt:manifest.createdAt,appVersion:manifest.appVersion,profiles:manifest.profiles}}catch(error){rmSync(pending,{recursive:true,force:true});throw error}}

export function applyPendingPortableRestore(appDataPath:string){const pending=join(appDataPath,PENDING_DIRECTORY),manifestPath=join(pending,"pending.json");if(!existsSync(manifestPath))return false;const manifest=JSON.parse(readFileSync(manifestPath,"utf8")) as {activeProfile:LocalDataProfile;profiles:Array<{id:LocalDataProfile;database:boolean;secrets:boolean}>};const state=profileState(appDataPath,manifest.activeProfile),stamp=new Date().toISOString().replace(/[:.]/g,"-");for(const included of manifest.profiles){if(!included.database)continue;const profile=state.profiles.find(value=>value.id===included.id);if(!profile)throw new Error("The pending restore contains an unsupported profile.");const staged=join(pending,profile.id);for(const name of ["gruhswad-admin.db","secrets.bin"]){const source=join(staged,name),target=join(profile.userDataPath,name);mkdirSync(dirname(target),{recursive:true});if(existsSync(target))renameSync(target,`${target}.pre-portable-${stamp}`);if(existsSync(source))renameSync(source,target)}const receiptSource=join(staged,"receipts"),receiptTarget=join(profile.userDataPath,"receipts");if(existsSync(receiptTarget))renameSync(receiptTarget,`${receiptTarget}.pre-portable-${stamp}`);if(existsSync(receiptSource))renameSync(receiptSource,receiptTarget);else mkdirSync(receiptTarget,{recursive:true})}const managed=join(pending,"managed-environment.json"),managedTarget=join(appDataPath,"gruhswad-admin-managed-environment.json");if(existsSync(managed)){if(existsSync(managedTarget))renameSync(managedTarget,`${managedTarget}.pre-portable-${stamp}`);renameSync(managed,managedTarget)}writeSelectedProfile(state.selectionPath,manifest.activeProfile);rmSync(pending,{recursive:true,force:true});return true}
export function discardPendingPortableRestore(appDataPath:string){rmSync(join(appDataPath,PENDING_DIRECTORY),{recursive:true,force:true})}

export function applyPendingPortableRestoreSafely(appDataPath:string){const pending=join(appDataPath,PENDING_DIRECTORY),manifestPath=join(pending,"pending.json");if(!existsSync(manifestPath))return false;const manifest=JSON.parse(readFileSync(manifestPath,"utf8")) as {activeProfile:LocalDataProfile;profiles:Array<{id:LocalDataProfile;database:boolean}>},state=profileState(appDataPath,manifest.activeProfile),stamp=new Date().toISOString().replace(/[:.]/g,"-"),operations:Array<{source:string|null;target:string;safety:string}> = [];for(const included of manifest.profiles){if(!included.database)continue;const profile=state.profiles.find(value=>value.id===included.id);if(!profile)throw new Error("The pending restore contains an unsupported profile.");const staged=join(pending,profile.id),receiptSource=join(staged,"receipts");mkdirSync(receiptSource,{recursive:true});for(const name of ["gruhswad-admin.db","secrets.bin","receipts"]){const source=join(staged,name),target=join(profile.userDataPath,name);if(name==="gruhswad-admin.db"&&!existsSync(source))throw new Error(`The ${included.id} database is missing from the pending restore.`);operations.push({source:existsSync(source)?source:null,target,safety:`${target}.pre-portable-${stamp}`})}}const managedSource=join(pending,"managed-environment.json"),managedTarget=join(appDataPath,"gruhswad-admin-managed-environment.json");operations.push({source:existsSync(managedSource)?managedSource:null,target:managedTarget,safety:`${managedTarget}.pre-portable-${stamp}`});try{for(const operation of operations){mkdirSync(dirname(operation.target),{recursive:true});if(existsSync(operation.target))renameSync(operation.target,operation.safety)}for(const operation of operations)if(operation.source)renameSync(operation.source,operation.target);writeSelectedProfile(state.selectionPath,manifest.activeProfile);rmSync(pending,{recursive:true,force:true});return true}catch(error){for(const operation of [...operations].reverse()){rmSync(operation.target,{recursive:true,force:true});if(existsSync(operation.safety))renameSync(operation.safety,operation.target)}throw error}}
