import { integer, real, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const menuCategories = sqliteTable("menu_categories", { id: text("id").primaryKey(), name: text("name").notNull(), sortOrder: integer("sort_order").notNull() });
export const menuItems = sqliteTable("menu_items", { id: text("id").primaryKey(), categoryId: text("category_id").notNull(), name: text("name").notNull(), description: text("description").notNull(), portion: text("portion").notNull(), price: real("price").notNull(), image: text("image"), available: integer("available", { mode: "boolean" }).notNull(), webCompatible: integer("web_compatible", { mode: "boolean" }).notNull() });
export const customers = sqliteTable("customers", { id: text("id").primaryKey(), name: text("name").notNull(), phone: text("phone").notNull().unique(), address: text("address"), createdAt: text("created_at").notNull() });
export const orders = sqliteTable("orders", { id: text("id").primaryKey(), customerId: text("customer_id").notNull(), serviceDate: text("service_date").notNull(), fulfilment: text("fulfilment").notNull(), address: text("address"), notes: text("notes"), source: text("source").notNull(), status: text("status").notNull(), paymentStatus: text("payment_status").notNull(), total: real("total").notNull(), createdAt: text("created_at").notNull(), updatedAt: text("updated_at").notNull() });
export const orderLines = sqliteTable("order_lines", { id: text("id").primaryKey(), orderId: text("order_id").notNull(), menuItemId: text("menu_item_id"), name: text("name").notNull(), quantity: integer("quantity").notNull(), unitPrice: real("unit_price").notNull(), lineTotal: real("line_total").notNull() });
export const payments = sqliteTable("payments", { id: text("id").primaryKey(), orderId: text("order_id").notNull(), amount: real("amount").notNull(), receivedAt: text("received_at").notNull(), method: text("method").notNull(), status: text("status").notNull() });
export const expenses = sqliteTable("expenses", { id: text("id").primaryKey(), date: text("date").notNull(), category: text("category").notNull(), description: text("description").notNull(), amount: real("amount").notNull(), paymentMethod: text("payment_method").notNull(), notes: text("notes") });
export const publications = sqliteTable("menu_publications", { id: text("id").primaryKey(), serviceDate: text("service_date").notNull(), payload: text("payload").notNull(), publishedAt: text("published_at").notNull() });
export const whatsappImports = sqliteTable("whatsapp_imports", { id: text("id").primaryKey(), metaMessageId: text("meta_message_id").notNull().unique(), sender: text("sender").notNull(), message: text("message").notNull(), parsedPayload: text("parsed_payload"), status: text("status").notNull(), orderId: text("order_id"), receivedAt: text("received_at").notNull() });
export const settings = sqliteTable("settings", { key: text("key").primaryKey(), value: text("value").notNull() });
