import { createHash, randomUUID } from "node:crypto";
import { neon } from "@neondatabase/serverless";
import { catalogItemSchema, publicationSchema, runtimeConfigSchema, type PushPreview, type SyncPreview } from "../shared/contracts";
import { normalizeServiceDate, normalizeTimestamp } from "../shared/dates";
import { classifyPushCandidates, emptyPushSectionCounts, pushSectionFor, pushSectionLabels, pushSectionKeys, type PushSectionCounts } from "../shared/push-policy";
import { normalizeRuntimeSetting } from "../shared/runtime-config";
import { syncAttentionFromCounts } from "../shared/sync-attention";
import { getCatalog, getCurrentPublication, getRuntimeConfig, rawDatabase } from "./database";
import { databaseConnection, databaseConnectionInfo, loadSecrets } from "./services";

type Row = Record<string, any>;
type RemoteSnapshot = { categories: Row[]; items: Row[]; groups: Row[]; choices: Row[]; settings: Row[]; publications: Row[]; customers: Row[]; addresses: Row[]; orders: Row[]; lines: Row[]; events: Row[] };
const hash = (value: unknown) => createHash("sha256").update(JSON.stringify(value)).digest("hex");
const json = (value: unknown) => JSON.stringify(value ?? null);

function connection() { const url = databaseConnection().url; if (!url) throw new Error("Configure a rotated least-privilege Neon sync URL in Settings."); return neon(url); }
async function fetchRemote(): Promise<RemoteSnapshot> {
  const sql = connection();
  const result = await sql.transaction([
    sql`SELECT * FROM catalog_categories ORDER BY display_order`, sql`SELECT * FROM catalog_items ORDER BY display_order,name`,
    sql`SELECT * FROM bundle_option_groups ORDER BY display_order`, sql`SELECT * FROM bundle_option_choices ORDER BY display_order`,
    sql`SELECT * FROM app_settings`, sql`SELECT * FROM menu_publications WHERE publication_key='current'`,
    sql`SELECT * FROM customers ORDER BY created_at`, sql`SELECT * FROM customer_addresses ORDER BY created_at`,
    sql`SELECT * FROM orders ORDER BY created_at`, sql`SELECT * FROM order_lines ORDER BY id`, sql`SELECT * FROM order_events ORDER BY id`,
  ]);
  return { categories: result[0], items: result[1], groups: result[2], choices: result[3], settings: result[4], publications: result[5], customers: result[6], addresses: result[7], orders: result[8], lines: result[9], events: result[10] } as RemoteSnapshot;
}

function itemPayload(row: Row, snapshot: RemoteSnapshot) {
  const groups = snapshot.groups.filter((group) => group.item_id === row.id).map((group) => ({ id: String(group.id), name: String(group.name), minChoices: Number(group.min_choices), maxChoices: Number(group.max_choices), order: Number(group.display_order), choices: snapshot.choices.filter((choice) => choice.group_id === group.id).map((choice) => ({ id: String(choice.id), itemId: String(choice.item_id), name: String(snapshot.items.find((item) => item.id === choice.item_id)?.name ?? ""), upgradePrice: Number(choice.upgrade_price), available: Boolean(choice.available), order: Number(choice.display_order) })) }));
  return catalogItemSchema.parse({ id: String(row.id), categoryId: String(row.category_id), type: row.item_type, name: String(row.name), description: String(row.description), portion: String(row.portion), price: Number(row.base_price), image: row.image_asset ? String(row.image_asset) : undefined, available: Boolean(row.available), isNew: Boolean(row.is_new), archived: Boolean(row.archived_at), tags: Array.isArray(row.tags) ? row.tags : [], order: Number(row.display_order), bundleGroups: groups });
}
function remoteEntities(snapshot: RemoteSnapshot) {
  const entities: { type: string; id: string; payload: any; version: string | null }[] = [];
  for (const row of snapshot.categories) entities.push({ type: "catalog_category", id: String(row.id), payload: { id: String(row.id), name: String(row.name), order: Number(row.display_order), active: Boolean(row.active) }, version: row.updated_at ? String(row.updated_at) : null });
  for (const row of snapshot.items) entities.push({ type: "catalog_item", id: String(row.id), payload: itemPayload(row, snapshot), version: row.updated_at ? String(row.updated_at) : null });
  for (const row of snapshot.settings) entities.push({ type: "app_setting", id: String(row.settings_key), payload: row.payload, version: row.updated_at ? String(row.updated_at) : null });
  if (snapshot.publications[0]) entities.push({ type: "publication", id: "current", payload: publicationSchema.parse(snapshot.publications[0].payload), version: String(snapshot.publications[0].published_at ?? "") });
  for(const row of snapshot.customers)entities.push({type:"cloud_customer",id:String(row.id),payload:{id:String(row.id),name:String(row.name),phone:String(row.phone_e164),email:row.email?String(row.email):null,archived:Boolean(row.archived_at),createdAt:String(row.created_at),updatedAt:String(row.updated_at)},version:row.updated_at?String(row.updated_at):null});
  return entities;
}
function localEntity(type: string, id: string): any {
  const db = rawDatabase();
  if (type === "catalog_category") { const row = db.prepare("SELECT id,name,sort_order AS 'order',active FROM menu_categories WHERE id=?").get(id) as any; return row ? { ...row, active: Boolean(row.active) } : null; }
  if (type === "catalog_item") { const item=getCatalog().items.find((entry) => entry.id === id); return item ? catalogItemSchema.parse(item) : null; }
  if (type === "app_setting") { const row = db.prepare("SELECT payload FROM app_settings WHERE settings_key=?").get(id) as any; return row ? JSON.parse(row.payload) : null; }
  if (type === "publication") return getCurrentPublication();
  if(type==="cloud_customer"){const row=rawDatabase().prepare("SELECT id,name,phone_e164 phone,email,archived_at,created_at,updated_at FROM cloud_customers WHERE id=?").get(id) as any;return row?{id:row.id,name:row.name,phone:row.phone,email:row.email??null,archived:Boolean(row.archived_at),createdAt:row.created_at,updatedAt:row.updated_at}:null;}
  if (type === "cloud_order_status") { const row = db.prepare("SELECT operational_status status FROM cloud_orders WHERE id=?").get(id) as any; return row ?? null; }
  return null;
}
function syncState(type: string, id: string) { return rawDatabase().prepare("SELECT * FROM sync_state WHERE entity_type=? AND entity_id=?").get(type, id) as any; }
function recordConflict(type: string, id: string, base: unknown, local: unknown, remote: unknown) { const db = rawDatabase(); db.prepare("DELETE FROM sync_conflicts WHERE entity_type=? AND entity_id=? AND resolved_at IS NULL").run(type, id); db.prepare("INSERT INTO sync_conflicts(id,entity_type,entity_id,base_payload,local_payload,remote_payload,created_at) VALUES(?,?,?,?,?,?,?)").run(randomUUID(), type, id, json(base), json(local), json(remote), new Date().toISOString()); }
function setClean(type: string, id: string, payload: unknown, version: string | null, direction: "pull" | "push") { const now = new Date().toISOString(); rawDatabase().prepare(`INSERT INTO sync_state(entity_type,entity_id,base_hash,base_payload,remote_version,dirty,${direction === "pull" ? "last_pulled_at" : "last_pushed_at"}) VALUES(?,?,?,?,?,0,?) ON CONFLICT(entity_type,entity_id) DO UPDATE SET base_hash=excluded.base_hash,base_payload=excluded.base_payload,remote_version=excluded.remote_version,dirty=0,${direction === "pull" ? "last_pulled_at" : "last_pushed_at"}=excluded.${direction === "pull" ? "last_pulled_at" : "last_pushed_at"}`).run(type, id, hash(payload), json(payload), version, now); }

function applyRemoteEntity(entity: ReturnType<typeof remoteEntities>[number]) {
  const db = rawDatabase(), value = entity.payload;
  if (entity.type === "catalog_category") db.prepare("INSERT INTO menu_categories(id,name,sort_order,active,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,sort_order=excluded.sort_order,active=excluded.active,updated_at=excluded.updated_at").run(value.id, value.name, value.order, value.active ? 1 : 0, entity.version);
  if (entity.type === "catalog_item") { db.prepare("INSERT INTO menu_items(id,category_id,item_type,name,description,portion,price,image,available,is_new,tags,display_order,archived_at,web_compatible,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET category_id=excluded.category_id,item_type=excluded.item_type,name=excluded.name,description=excluded.description,portion=excluded.portion,price=excluded.price,image=excluded.image,available=excluded.available,is_new=excluded.is_new,tags=excluded.tags,display_order=excluded.display_order,archived_at=excluded.archived_at,updated_at=excluded.updated_at").run(value.id,value.categoryId,value.type,value.name,value.description,value.portion,value.price,value.image??null,value.available?1:0,value.isNew?1:0,json(value.tags),value.order,value.archived?entity.version:null,1,entity.version); db.prepare("DELETE FROM bundle_option_groups WHERE item_id=?").run(value.id); }
  if (entity.type === "app_setting") db.prepare("INSERT INTO app_settings(settings_key,payload,updated_at) VALUES(?,?,?) ON CONFLICT(settings_key) DO UPDATE SET payload=excluded.payload,updated_at=excluded.updated_at").run(entity.id,json(normalizeRuntimeSetting(entity.id,value)),entity.version);
  if (entity.type === "publication") db.prepare("INSERT INTO current_publication(publication_key,payload,published_at) VALUES('current',?,?) ON CONFLICT(publication_key) DO UPDATE SET payload=excluded.payload,published_at=excluded.published_at").run(json(value),entity.version);
  if(entity.type==="cloud_customer"){db.prepare("INSERT INTO cloud_customers(id,firebase_uid,phone_e164,name,email,archived_at,verified_at,created_at,updated_at) VALUES(?,NULL,?,?,?,?,NULL,?,?) ON CONFLICT(id) DO UPDATE SET phone_e164=excluded.phone_e164,name=excluded.name,email=excluded.email,archived_at=excluded.archived_at,created_at=excluded.created_at,updated_at=excluded.updated_at").run(value.id,value.phone,value.name,value.email,value.archived?value.updatedAt:null,value.createdAt,value.updatedAt);db.prepare("INSERT INTO customers(id,name,phone,email,address,archived_at,created_at,updated_at) VALUES(?,?,?,?,NULL,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,phone=excluded.phone,email=excluded.email,archived_at=excluded.archived_at,updated_at=excluded.updated_at").run(value.id,value.name,value.phone,value.email,value.archived?value.updatedAt:null,value.createdAt,value.updatedAt);}
  if (entity.type === "cloud_order_status") db.prepare("UPDATE cloud_orders SET operational_status=?,status=?,updated_at=COALESCE(?,updated_at) WHERE id=?").run(value.status,value.status,entity.version,entity.id);
}
function applyCatalogBundles(snapshot:RemoteSnapshot){const db=rawDatabase(),group=db.prepare("INSERT INTO bundle_option_groups(id,item_id,name,min_choices,max_choices,display_order) VALUES(?,?,?,?,?,?)"),choice=db.prepare("INSERT INTO bundle_option_choices(id,group_id,item_id,upgrade_price,available,display_order) VALUES(?,?,?,?,?,?)");for(const item of snapshot.items){const value=itemPayload(item,snapshot);for(const entry of value.bundleGroups){group.run(entry.id,value.id,entry.name,entry.minChoices,entry.maxChoices,entry.order);for(const option of entry.choices)choice.run(option.id,entry.id,option.itemId,option.upgradePrice,option.available?1:0,option.order)}}}
function applyCloudMirrors(snapshot: RemoteSnapshot) {
  const db=rawDatabase();
  const address=db.prepare("INSERT INTO cloud_customer_addresses(id,customer_id,place_id,formatted_address,latitude,longitude,city,state,country,is_default,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET customer_id=excluded.customer_id,place_id=excluded.place_id,formatted_address=excluded.formatted_address,latitude=excluded.latitude,longitude=excluded.longitude,city=excluded.city,state=excluded.state,country=excluded.country,is_default=excluded.is_default,created_at=excluded.created_at,updated_at=excluded.updated_at");
  for(const row of snapshot.addresses)address.run(String(row.id),String(row.customer_id),String(row.place_id),String(row.formatted_address),Number(row.latitude),Number(row.longitude),String(row.city),String(row.state),String(row.country),row.is_default?1:0,String(row.created_at),String(row.updated_at));
  const order=db.prepare("INSERT INTO cloud_orders(id,order_number,idempotency_key,customer_id,publication_key,service_date,fulfilment,customer_snapshot,address_snapshot,source_mode,subtotal,total,notes,status,handoff_status,operational_status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET order_number=excluded.order_number,idempotency_key=excluded.idempotency_key,customer_id=excluded.customer_id,publication_key=excluded.publication_key,service_date=excluded.service_date,fulfilment=excluded.fulfilment,customer_snapshot=excluded.customer_snapshot,address_snapshot=excluded.address_snapshot,source_mode=excluded.source_mode,subtotal=excluded.subtotal,total=excluded.total,notes=excluded.notes,status=excluded.status,handoff_status=excluded.handoff_status,operational_status=excluded.operational_status,created_at=excluded.created_at,updated_at=excluded.updated_at");
  for(const row of snapshot.orders){
    const id=String(row.id),legacy=String(row.status),operational=String(row.operational_status??(["handoff_created","customer_confirmed_sent"].includes(legacy)?"awaiting_review":legacy)),handoff=String(row.handoff_status??(legacy==="handoff_created"?"created":"customer_confirmed")),state=syncState("cloud_order_status",id);
    if(state?.dirty&&state.remote_version&&state.remote_version!==String(row.updated_at)){recordConflict("cloud_order_status",id,state.base_payload?JSON.parse(state.base_payload):null,localEntity("cloud_order_status",id),{status:operational});continue;}
    order.run(id,String(row.order_number),String(row.idempotency_key),row.customer_id?String(row.customer_id):null,String(row.publication_key),normalizeServiceDate(row.service_date),String(row.fulfilment),json(row.customer_snapshot),json(row.address_snapshot),String(row.source_mode),Number(row.subtotal),Number(row.total),String(row.notes),operational,handoff,operational,normalizeTimestamp(row.created_at),normalizeTimestamp(row.updated_at));
    setClean("cloud_order_status",id,{status:operational},String(row.updated_at),"pull");
  }
  db.prepare("DELETE FROM cloud_order_lines").run();
  const line=db.prepare("INSERT INTO cloud_order_lines(id,order_id,item_id,item_snapshot,bundle_selection,quantity,unit_total,line_total) VALUES(?,?,?,?,?,?,?,?)");
  for(const row of snapshot.lines)line.run(String(row.id),String(row.order_id),String(row.item_id),json(row.item_snapshot),json(row.bundle_selection),Number(row.quantity),Number(row.unit_total),Number(row.line_total));
  db.prepare("DELETE FROM cloud_order_events").run();
  const event=db.prepare("INSERT INTO cloud_order_events(id,order_id,event_type,payload,created_at) VALUES(?,?,?,?,?)");
  for(const row of snapshot.events)event.run(String(row.id),String(row.order_id),String(row.event_type),json(row.payload),normalizeTimestamp(row.created_at));
}

export async function previewPull():Promise<SyncPreview>{const snapshot=await fetchRemote(),entities=remoteEntities(snapshot),result:SyncPreview={inserts:0,updates:0,conflicts:0,dirty:0,entities:[]};for(const entity of entities){const local=localEntity(entity.type,entity.id),state=syncState(entity.type,entity.id);if(!local){result.inserts++;result.entities.push({type:entity.type,id:entity.id,action:"insert"});}else if(hash(local)!==hash(entity.payload)){if(state?.dirty){if(entity.type==="cloud_customer"&&state.remote_version===entity.version)continue;result.conflicts++;result.entities.push({type:entity.type,id:entity.id,action:"conflict"});}else{result.updates++;result.entities.push({type:entity.type,id:entity.id,action:"update"});}}}result.dirty=(rawDatabase().prepare("SELECT COUNT(*) count FROM sync_state WHERE dirty=1").get() as any).count;return result;}
let activePull:Promise<SyncPreview>|null=null;
async function performPull():Promise<SyncPreview>{const runId=randomUUID(),now=new Date().toISOString(),db=rawDatabase();db.prepare("INSERT INTO sync_runs(id,direction,status,started_at) VALUES(?,'pull','running',?)").run(runId,now);try{const snapshot=await fetchRemote(),preview=await calculatePreview(snapshot);db.transaction(()=>{for(const entity of remoteEntities(snapshot)){const local=localEntity(entity.type,entity.id),state=syncState(entity.type,entity.id);if(state?.dirty&&local&&hash(local)!==hash(entity.payload)){if(entity.type==="cloud_customer"&&state.remote_version===entity.version)continue;recordConflict(entity.type,entity.id,state.base_payload?JSON.parse(state.base_payload):null,local,entity.payload);continue;}applyRemoteEntity(entity);setClean(entity.type,entity.id,entity.payload,entity.version,"pull");}applyCatalogBundles(snapshot);applyCloudMirrors(snapshot);})();db.prepare("UPDATE sync_runs SET status='complete',completed_at=?,inserted_count=?,updated_count=?,conflict_count=? WHERE id=?").run(new Date().toISOString(),preview.inserts,preview.updates,preview.conflicts,runId);return preview;}catch(error){db.prepare("UPDATE sync_runs SET status='failed',completed_at=?,error=? WHERE id=?").run(new Date().toISOString(),String(error),runId);throw error;}}
export function pullFromNeon():Promise<SyncPreview>{if(activePull)return activePull;activePull=performPull().finally(()=>{activePull=null;});return activePull;}
async function calculatePreview(snapshot:RemoteSnapshot){const result:SyncPreview={inserts:0,updates:0,conflicts:0,dirty:0,entities:[]};for(const entity of remoteEntities(snapshot)){const local=localEntity(entity.type,entity.id),state=syncState(entity.type,entity.id);if(!local){result.inserts++;result.entities.push({type:entity.type,id:entity.id,action:"insert"});}else if(hash(local)!==hash(entity.payload)){if(state?.dirty&&entity.type==="cloud_customer"&&state.remote_version===entity.version)continue;const action=state?.dirty?"conflict":"update";action==="conflict"?result.conflicts++:result.updates++;result.entities.push({type:entity.type,id:entity.id,action});}}result.dirty=(rawDatabase().prepare("SELECT COUNT(*) count FROM sync_state WHERE dirty=1").get() as any).count;return result;}

function unresolvedPushConflicts() {
  const rows = rawDatabase().prepare("SELECT entity_type type,entity_id id FROM sync_conflicts WHERE resolved_at IS NULL").all() as {type:string;id:string}[];
  return rows.filter((row) => pushSectionFor(row.type, row.id));
}

export function previewPush():PushPreview {
  const rows = rawDatabase().prepare("SELECT entity_type type,entity_id id FROM sync_state WHERE dirty=1 ORDER BY entity_type,entity_id").all() as {type:string;id:string}[];
  const classified = classifyPushCandidates(rows);
  return {
    inserts: 0,
    updates: classified.pushable.length,
    conflicts: unresolvedPushConflicts().length,
    dirty: rows.length,
    pushableDirty: classified.pushable.length,
    excludedDirty: classified.excluded.length,
    sections: classified.sections,
    entities: [
      ...classified.pushable.map(({type,id}) => ({type,id,action:"push"})),
      ...classified.excluded.map(({type,id}) => ({type,id,action:"excluded"})),
    ],
  };
}

export function syncAttention() {
  const conflicts = (rawDatabase().prepare("SELECT COUNT(*) count FROM sync_conflicts WHERE resolved_at IS NULL").get() as { count: number }).count;
  return syncAttentionFromCounts(conflicts, previewPush().pushableDirty);
}

function auditSummary(sections:PushSectionCounts, excluded:number) {
  return [...pushSectionKeys.map((key) => `${pushSectionLabels[key]} ${sections[key]}`), `Excluded ${excluded}`].join(" | ");
}

export async function pushToNeon():Promise<PushPreview>{const preview=previewPush();if(preview.conflicts)throw new Error("Resolve conflicts in pushable records before pushing.");const sql=connection(),db=rawDatabase(),runId=randomUUID(),pushed=emptyPushSectionCounts();db.prepare("INSERT INTO sync_runs(id,direction,status,started_at) VALUES(?,'push','running',?)").run(runId,new Date().toISOString());try{const dirty=(db.prepare("SELECT * FROM sync_state WHERE dirty=1").all() as any[]).filter((state)=>pushSectionFor(state.entity_type,state.entity_id));for(const state of dirty){const section=pushSectionFor(state.entity_type,state.entity_id);if(!section)continue;const local=localEntity(state.entity_type,state.entity_id);if(!local)continue;if(state.entity_type==="catalog_category"){const category={id:String(local.id),name:String(local.name).trim(),order:Number(local.order),active:Boolean(local.active)};if(!category.id||!category.name||!Number.isInteger(category.order))throw new Error(`Catalog category ${state.entity_id} is invalid.`);const remote=await sql`SELECT id,name,display_order,active,updated_at FROM catalog_categories WHERE id=${category.id}`;if(state.remote_version&&remote[0]&&String(remote[0].updated_at)!==state.remote_version){recordConflict(state.entity_type,state.entity_id,state.base_payload?JSON.parse(state.base_payload):null,category,{id:String(remote[0].id),name:String(remote[0].name),order:Number(remote[0].display_order),active:Boolean(remote[0].active)});continue;}await sql`INSERT INTO catalog_categories(id,name,display_order,active,updated_at) VALUES(${category.id},${category.name},${category.order},${category.active},NOW()) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,display_order=EXCLUDED.display_order,active=EXCLUDED.active,updated_at=NOW()`;const updated=await sql`SELECT updated_at FROM catalog_categories WHERE id=${category.id}`;setClean(state.entity_type,state.entity_id,category,String(updated[0].updated_at),"push");pushed[section]++;}
      if(state.entity_type==="cloud_customer"){const columns=await sql`SELECT column_name FROM information_schema.columns WHERE table_schema='public' AND table_name='customers' AND column_name IN ('email','archived_at')`;if(columns.length<2)throw new Error("Neon customer migration is required. Apply neon-migrations/0001_customer_directory.sql with a database owner before pushing customers.");const remote=await sql`SELECT id,name,phone_e164,email,archived_at,created_at,updated_at FROM customers WHERE id=${local.id}`;if(state.remote_version&&remote[0]&&String(remote[0].updated_at)!==state.remote_version){recordConflict(state.entity_type,state.entity_id,state.base_payload?JSON.parse(state.base_payload):null,local,{id:String(remote[0].id),name:String(remote[0].name),phone:String(remote[0].phone_e164),email:remote[0].email?String(remote[0].email):null,archived:Boolean(remote[0].archived_at),createdAt:String(remote[0].created_at),updatedAt:String(remote[0].updated_at)});continue;}await sql`INSERT INTO customers(id,firebase_uid,phone_e164,name,email,archived_at,verified_at,created_at,updated_at) VALUES(${local.id},NULL,${local.phone},${local.name},${local.email},${local.archived?new Date():null},NULL,${local.createdAt},NOW()) ON CONFLICT(id) DO UPDATE SET phone_e164=EXCLUDED.phone_e164,name=EXCLUDED.name,email=EXCLUDED.email,archived_at=EXCLUDED.archived_at,updated_at=NOW()`;const updated=await sql`SELECT created_at,updated_at FROM customers WHERE id=${local.id}`;const clean={...local,createdAt:String(updated[0].created_at),updatedAt:String(updated[0].updated_at)};rawDatabase().prepare("UPDATE cloud_customers SET created_at=?,updated_at=? WHERE id=?").run(clean.createdAt,clean.updatedAt,local.id);setClean(state.entity_type,state.entity_id,clean,String(updated[0].updated_at),"push");pushed[section]++;}
      if(state.entity_type==="catalog_item"){const item=catalogItemSchema.parse(local),remote=await sql`SELECT updated_at FROM catalog_items WHERE id=${item.id}`;if(state.remote_version&&remote[0]&&String(remote[0].updated_at)!==state.remote_version){const snapshot=await fetchRemote(),remoteRow=snapshot.items.find((entry)=>String(entry.id)===item.id);recordConflict(state.entity_type,state.entity_id,state.base_payload?JSON.parse(state.base_payload):null,item,remoteRow?itemPayload(remoteRow,snapshot):null);continue;}await sql.transaction([sql`INSERT INTO catalog_items(id,category_id,item_type,name,description,portion,base_price,image_asset,available,is_new,tags,display_order,archived_at,updated_at) VALUES(${item.id},${item.categoryId},${item.type},${item.name},${item.description},${item.portion},${item.price},${item.image??"food-placeholder.jpeg"},${item.available},${item.isNew},${json(item.tags)}::jsonb,${item.order},${item.archived?new Date():null},NOW()) ON CONFLICT(id) DO UPDATE SET category_id=EXCLUDED.category_id,item_type=EXCLUDED.item_type,name=EXCLUDED.name,description=EXCLUDED.description,portion=EXCLUDED.portion,base_price=EXCLUDED.base_price,image_asset=EXCLUDED.image_asset,available=EXCLUDED.available,is_new=EXCLUDED.is_new,tags=EXCLUDED.tags,display_order=EXCLUDED.display_order,archived_at=EXCLUDED.archived_at,updated_at=NOW()`,sql`DELETE FROM bundle_option_groups WHERE item_id=${item.id}`]);for(const group of item.bundleGroups){await sql`INSERT INTO bundle_option_groups(id,item_id,name,min_choices,max_choices,display_order) VALUES(${group.id},${item.id},${group.name},${group.minChoices},${group.maxChoices},${group.order})`;for(const choice of group.choices)await sql`INSERT INTO bundle_option_choices(id,group_id,item_id,upgrade_price,available,display_order) VALUES(${choice.id},${group.id},${choice.itemId},${choice.upgradePrice},${choice.available},${choice.order})`;}const updated=await sql`SELECT updated_at FROM catalog_items WHERE id=${item.id}`;setClean(state.entity_type,state.entity_id,item,String(updated[0].updated_at),"push");pushed[section]++;}
      if(state.entity_type==="app_setting"){const remote=await sql`SELECT payload,updated_at FROM app_settings WHERE settings_key=${state.entity_id}`;if(state.remote_version&&remote[0]&&String(remote[0].updated_at)!==state.remote_version){recordConflict(state.entity_type,state.entity_id,state.base_payload?JSON.parse(state.base_payload):null,local,remote[0].payload);continue;}await sql`INSERT INTO app_settings(settings_key,payload,updated_at) VALUES(${state.entity_id},${json(local)}::jsonb,NOW()) ON CONFLICT(settings_key) DO UPDATE SET payload=EXCLUDED.payload,updated_at=NOW()`;const updated=await sql`SELECT updated_at FROM app_settings WHERE settings_key=${state.entity_id}`;setClean(state.entity_type,state.entity_id,local,String(updated[0].updated_at),"push");pushed[section]++;}
      if(state.entity_type==="publication"){const publication=publicationSchema.parse(local),remote=await sql`SELECT payload,published_at FROM menu_publications WHERE publication_key='current'`;if(state.remote_version&&remote[0]&&String(remote[0].published_at)!==state.remote_version){recordConflict(state.entity_type,state.entity_id,state.base_payload?JSON.parse(state.base_payload):null,publication,remote[0].payload);continue;}await sql`INSERT INTO menu_publications(publication_key,payload,published_at) VALUES('current',${json(publication)}::jsonb,NOW()) ON CONFLICT(publication_key) DO UPDATE SET payload=EXCLUDED.payload,published_at=NOW()`;const updated=await sql`SELECT published_at FROM menu_publications WHERE publication_key='current'`;setClean(state.entity_type,state.entity_id,publication,String(updated[0].published_at),"push");pushed[section]++;}
      if(state.entity_type==="cloud_order_status"){const remote=await sql`SELECT operational_status status,updated_at FROM orders WHERE id=${state.entity_id}`;if(!remote[0])throw new Error(`Neon order ${state.entity_id} no longer exists.`);if(state.remote_version&&String(remote[0].updated_at)!==state.remote_version){recordConflict(state.entity_type,state.entity_id,state.base_payload?JSON.parse(state.base_payload):null,local,{status:String(remote[0].status)});continue;}await sql`SELECT gruhswad_transition_order(${state.entity_id}::uuid,${local.status})`;const updated=await sql`SELECT updated_at FROM orders WHERE id=${state.entity_id}`;setClean(state.entity_type,state.entity_id,local,String(updated[0].updated_at),"push");pushed[section]++;}}
    const remaining=unresolvedPushConflicts().length,totalPushed=pushSectionKeys.reduce((sum,key)=>sum+pushed[key],0),summary=auditSummary(pushed,preview.excludedDirty);db.prepare("UPDATE sync_runs SET status=?,completed_at=?,updated_count=?,conflict_count=?,summary=? WHERE id=?").run(remaining?"partial":"complete",new Date().toISOString(),totalPushed,remaining,summary,runId);return{...preview,updates:totalPushed,sections:pushed,conflicts:remaining};}catch(error){db.prepare("UPDATE sync_runs SET status='failed',completed_at=?,error=?,summary=? WHERE id=?").run(new Date().toISOString(),String(error),auditSummary(pushed,preview.excludedDirty),runId);throw error;}}

export async function syncStatus(){const db=rawDatabase(),connection=databaseConnectionInfo();let online=false;if(!connection.error){const secrets=loadSecrets();if(secrets.neonDatabaseUrl){try{const sql=neon(secrets.neonDatabaseUrl);await sql`SELECT 1`;online=true;}catch{online=false;}}}const dirty=(db.prepare("SELECT COUNT(*) count FROM sync_state WHERE dirty=1").get() as any).count,conflicts=(db.prepare("SELECT COUNT(*) count FROM sync_conflicts WHERE resolved_at IS NULL").get() as any).count,runs=db.prepare("SELECT * FROM sync_runs ORDER BY started_at DESC LIMIT 20").all() as any[];return{online,dirty,conflicts,lastPull:runs.find((run)=>run.direction==="pull"&&run.status==="complete")?.completed_at??null,lastPush:runs.find((run)=>run.direction==="push"&&run.status==="complete")?.completed_at??null,runs,connection};}
export function listConflicts(){return rawDatabase().prepare("SELECT * FROM sync_conflicts WHERE resolved_at IS NULL ORDER BY created_at DESC").all();}
export function resolveConflict(id:string,resolution:"local"|"neon"){const db=rawDatabase(),row=db.prepare("SELECT * FROM sync_conflicts WHERE id=? AND resolved_at IS NULL").get(id) as any;if(!row)throw new Error("Conflict not found.");const payload=JSON.parse(resolution==="local"?row.local_payload:row.remote_payload);if(resolution==="neon"){applyRemoteEntity({type:row.entity_type,id:row.entity_id,payload,version:null});setClean(row.entity_type,row.entity_id,payload,null,"pull");}else db.prepare("UPDATE sync_state SET dirty=1 WHERE entity_type=? AND entity_id=?").run(row.entity_type,row.entity_id);db.prepare("UPDATE sync_conflicts SET resolved_at=?,resolution=? WHERE id=?").run(new Date().toISOString(),resolution,id);}
export function syncHistory(){return rawDatabase().prepare("SELECT * FROM sync_runs ORDER BY started_at DESC LIMIT 100").all();}
