import React, { useState } from "react";
import type { CatalogCategory } from "../shared/contracts";

const blankCategory = (order: number): CatalogCategory => ({ id: "", name: "", order, active: true });

export function CategoryManagerModal({ categories, onClose, onSave, onToggle }: { categories: CatalogCategory[]; onClose(): void; onSave(category: CatalogCategory): Promise<void>; onToggle(category: CatalogCategory): Promise<void> }) {
  const [draft, setDraft] = useState<CatalogCategory | null>(null);
  const [saving, setSaving] = useState(false);
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!draft) return; setSaving(true); try { await onSave(draft); setDraft(null); } finally { setSaving(false); } }
  return <div className="modal-shell" role="dialog" aria-modal="true" aria-label="Manage categories"><button className="modal-backdrop" aria-label="Close category manager" onClick={onClose}/><section className="category-modal"><header><div><small>MASTER MENU</small><h2>Manage categories</h2></div><button onClick={onClose}>Close</button></header><div className="category-manager-body"><p className="muted">Inactive categories and their items stay stored, but are removed from publishing choices and the exported master menu.</p><div className="category-list">{categories.map((category)=><article className={category.active?"":"inactive"} key={category.id}><div><strong>{category.name}</strong><span>{category.id} / order {category.order}</span></div><button onClick={()=>setDraft({...category})}>Edit</button><button className={category.active?"danger":""} onClick={()=>onToggle(category)}>{category.active?"Remove":"Restore"}</button></article>)}</div>{draft?<form className="category-form" onSubmit={submit}><h3>{categories.some((category)=>category.id===draft.id)?"Edit category":"Add category"}</h3><label>Website ID<input required disabled={categories.some((category)=>category.id===draft.id)} value={draft.id} onChange={(event)=>setDraft({...draft,id:event.target.value.toLowerCase().replace(/[^a-z0-9-]+/g,"-")})}/></label><label>Name<input required value={draft.name} onChange={(event)=>setDraft({...draft,name:event.target.value})}/></label><label>Display order<input type="number" min="0" value={draft.order} onChange={(event)=>setDraft({...draft,order:Number(event.target.value)})}/></label><footer><button type="button" onClick={()=>setDraft(null)}>Cancel</button><button className="primary" disabled={saving}>{saving?"Saving...":"Save category"}</button></footer></form>:<button className="primary add-category" onClick={()=>setDraft(blankCategory(Math.max(0,...categories.map((category)=>category.order))+1))}>+ Add category</button>}</div></section></div>;
}
